-- ============================================================================
-- Seed Data: Podcasts (podcast episodes for both series)
-- Populates public.news with items for the "Podcasts" tab.
-- Items come from NewsItem where format = 'Podcast' (or tagged as podcasts).
-- ============================================================================

INSERT INTO public.news (
  id, title, type, date, author, byline, views, excerpt, image,
  department, location, domain, tags, reading_time, news_type, news_source,
  focus_area, content, format, source, audio_url
) VALUES
-- Action-Solver episode 1: Why Execution Beats Intelligence
(
  'why-execution-beats-intelligence',
  'Why Execution Beats Intelligence: The Real Driver of Growth in DQ',
  'Thought Leadership',
  '2024-12-01',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Explore how execution and consistent action drive real growth at DQ, and why intelligence alone isn''t enough to achieve organizational success.',
  'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Business',
  ARRAY['podcast','execution','growth','leadership','strategy'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Why Execution Beats Intelligence: The Real Driver of Growth in DQ — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/Podcasts/Execution_Beats_Intelligence__Why_Action_Wins.m4a'
),
-- Action-Solver episode 2: Why We Misdiagnose Problems — And How to Stop It
(
  'why-we-misdiagnose-problems',
  'Why We Misdiagnose Problems — And How to Stop It',
  'Thought Leadership',
  '2024-12-02',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Learn why teams often misdiagnose problems and discover practical frameworks to identify root causes and implement effective solutions.',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Business',
  ARRAY['podcast','problem-solving','diagnosis','root-cause','analysis'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: why-we-misdiagnose-problems — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/Podcasts/Why We Misdiagnose Problems — And How to Stop It.m4a'
),
-- Action-Solver episode 3: Turning Every Conversation Into Action
(
  'turning-conversations-into-action',
  'Turning Every Conversation Into Action',
  'Thought Leadership',
  '2024-12-03',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Discover how to transform meetings and discussions into concrete actions that drive progress and deliver results.',
  'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Business',
  ARRAY['podcast','conversation','action','meetings','productivity'],
  '10–20',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: turning-conversations-into-action — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/Podcasts/Turning_Every_Conversation _Into _Action.m4a'
),
-- Action-Solver episode 4: Why Tasks Don''t Close at DQ — And How to Fix It
(
  'why-tasks-dont-close-at-dq',
  'Why Tasks Don''t Close at DQ — And How to Fix It',
  'Thought Leadership',
  '2024-12-04',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'An in-depth analysis of why tasks remain open and practical solutions to improve task completion rates across DQ teams.',
  'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Operations',
  ARRAY['podcast','tasks','productivity','project-management','execution'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: why-tasks-dont-close-at-dq — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/Podcasts/Why_Smart_Teams_Fail_To_Finish.m4a'
),
-- Action-Solver episode 5: Happy Talkers: Why Talking Feels Productive but Isn''t
(
  'happy-talkers-why-talking-feels-productive',
  'Happy Talkers: Why Talking Feels Productive but Isn''t',
  'Thought Leadership',
  '2024-12-05',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Explore the phenomenon of "happy talking" and why excessive discussion can create an illusion of productivity without delivering real results.',
  'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Business',
  ARRAY['podcast','communication','productivity','meetings','culture'],
  '10–20',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: happy-talkers-why-talking-feels-productive — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/Podcasts/Stop_Happy_Talk_and_Start_Executing.m4a'
),
-- Action-Solver episode 6: Execution Styles: Why Teams Work Differently and How to Align Them
(
  'execution-styles-why-teams-work-differently',
  'Execution Styles: Why Teams Work Differently and How to Align Them',
  'Thought Leadership',
  '2024-12-06',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Understand different execution styles across teams and learn how to align diverse approaches for maximum effectiveness.',
  'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'People',
  ARRAY['podcast','execution','teams','collaboration','alignment'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: execution-styles-why-teams-work-differently — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/Podcasts/Stop_Judging_Intent_Coordinate_Work_Styles.m4a'
),
-- Action-Solver episode 7: Agile the DQ Way: Why Tasks Are the Core of Our Work System
(
  'agile-the-dq-way-tasks-core-work-system',
  'Agile the DQ Way: Why Tasks Are the Core of Our Work System',
  'Thought Leadership',
  '2024-12-07',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Learn how DQ implements Agile principles with tasks as the fundamental unit of work, driving clarity and accountability.',
  'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Operations',
  ARRAY['podcast','agile','tasks','work-system','methodology'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: agile-the-dq-way-tasks-core-work-system — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/Podcasts/Agile_is_Task_Movement_Not_Ceremony.m4a'
),
-- Action-Solver episode 8: Leaders as Multipliers: How to Accelerate Team Execution
(
  'leaders-as-multipliers-accelerate-execution',
  'Leaders as Multipliers: How to Accelerate Team Execution',
  'Thought Leadership',
  '2024-12-08',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Discover how leaders can act as multipliers, accelerating team execution and amplifying results through effective leadership practices.',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'People',
  ARRAY['podcast','leadership','multipliers','execution','team-performance'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: leaders-as-multipliers-accelerate-execution — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/Podcasts/Execution_Beats_Intelligence__Why_Action_Wins (1).m4a'
),
-- Action-Solver episode 9: Energy Management for High-Action Days
(
  'energy-management-for-high-action-days',
  'How to Manage Your Energy for High-Action Days',
  'Thought Leadership',
  '2024-12-19',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Learn how managing usable mental, emotional, and physical energy—not just time blocks—creates sustainable high-action days and reduces invisible stress.',
  'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'People',
  ARRAY['podcast','energy','performance','productivity','stress'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: energy-management-for-high-action-days — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/Podcasts/Stop_Clock_Watching_Start_Managing_Energy.m4a'
),
-- Action-Solver episode 10: Execution Metrics: How to Measure the Only Things That Matter
(
  'execution-metrics-that-drive-movement',
  'Execution Metrics: How to Measure the Only Things That Matter',
  'Thought Leadership',
  '2024-12-20',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Explore how to replace vanity metrics with execution metrics like Task Closure Rate, Time to First Action, and Blocker Age to drive real movement, unblock teams, and build a culture of improvement.',
  'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Operations',
  ARRAY['podcast','metrics','execution','performance','blockers'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: execution-metrics-that-drive-movement — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/Podcasts/The_Four_Metrics_That_Drive_Execution_Speed.m4a'
),
-- Execution Mindset series: Ownership Mindset (already present in data)
(
  'ownership-mindset-single-driver',
  'Ownership Mindset: Why Every Task Needs a Single Driver',
  'Thought Leadership',
  '2025-01-10',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Explore why every task needs a single, clearly named owner and how ownership mindset accelerates execution across teams.',
  NULL,
  'DQ Leadership',
  NULL,
  'People',
  ARRAY['podcast','execution mindset','ownership','series-2'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Ownership Mindset: Why Every Task Needs a Single Driver — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/02. Series 02 - The Execution Mindset/Ep 1_Ownership Mindset - Why Every Task Needs a Single Driver.m4a'
),
-- Execution Mindset episode 2: The Psychology of Follow-through
(
  'psychology-of-follow-through',
  'The Psychology of Follow-through: How to Finish What You Start',
  'Thought Leadership',
  '2025-01-11',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Understand the mental barriers that stop us from finishing and learn simple tools to close the loop on commitments.',
  'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'People',
  ARRAY['podcast','execution mindset','follow-through','series-2'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: psychology-of-follow-through — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/02. Series 02 - The Execution Mindset/Ep 2_The Psychology of Follow-through - How to Finish What You Start.m4a'
),
-- Execution Mindset episode 3: Don''t Mistake Motion for Progress
(
  'dont-mistake-motion-for-progress',
  'Don''t Mistake Motion for Progress',
  'Thought Leadership',
  '2025-01-12',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Learn to separate activity from real movement so you can stop spinning and start advancing meaningful work.',
  'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Business',
  ARRAY['podcast','execution mindset','focus','series-2'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: dont-mistake-motion-for-progress — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/02. Series 02 - The Execution Mindset/Don_t_Mistake_Motion_For_Progress (2).m4a'
),
-- Execution Mindset episode 4: Cutting the Noise (original recording)
(
  'cutting-the-noise-focus-habits',
  'Cutting the Noise: Focus Habits for Digital Workers',
  'Thought Leadership',
  '2025-01-13',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Practical focus habits for digital workers who are overwhelmed by pings, channels, and constant micro-requests.',
  'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'People',
  ARRAY['podcast','execution mindset','focus','digital workers','series-2'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: cutting-the-noise-focus-habits — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/02. Series 02 - The Execution Mindset/Ep 8_Cutting the Noise - Focus Habits for Digital Workers.m4a'
),
-- Execution Mindset episode 5: How to Build a High-Velocity Team Culture
(
  'build-high-velocity-team-culture',
  'How to Build a High-Velocity Team Culture',
  'Thought Leadership',
  '2025-01-14',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Explore the cultural rules and rituals that separate high-velocity teams from well-intentioned but slow ones.',
  'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Operations',
  ARRAY['podcast','execution mindset','team culture','series-2'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: build-high-velocity-team-culture — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/02. Series 02 - The Execution Mindset/Ep 9_How to Build a High-Velocity Team Culture.m4a'
),
-- Execution Mindset episode 6: Micro Actions Beat Big Plans
(
  'micro-actions-beat-big-plans',
  'Micro Actions Beat Big Plans',
  'Thought Leadership',
  '2025-01-15',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Why tiny, well-chosen moves out-perform grand plans that never quite get off the ground.',
  'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Business',
  ARRAY['podcast','execution mindset','micro actions','series-2'],
  '10–20',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: micro-actions-beat-big-plans — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/02. Series 02 - The Execution Mindset/Micro_Actions_Beat_Big_Plans (1).m4a'
),
-- Execution Mindset episode 7: Micro-Actions: Converting Intention into Traction
(
  'micro-actions-convert-intention-into-traction',
  'Micro-Actions: Converting Intention into Traction',
  'Thought Leadership',
  '2025-01-16',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'A practical walkthrough of how to turn vague intentions into small, trackable movements that compound.',
  'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Business',
  ARRAY['podcast','execution mindset','traction','series-2'],
  '10–20',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: micro-actions-convert-intention-into-traction — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/02. Series 02 - The Execution Mindset/Micro-Actions_Convert_Intention_Into_Traction.m4a'
),
-- Execution Mindset episode 8: Stop Discussion, Start Action Through Clarity
(
  'stop-discussion-start-action-clarity',
  'Stop Discussion, Start Action Through Clarity',
  'Thought Leadership',
  '2025-01-17',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Why unclear ownership, fuzzy outcomes, and vague next steps keep teams in discussion loops instead of decisive action.',
  'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'Business',
  ARRAY['podcast','execution mindset','clarity','series-2'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: stop-discussion-start-action-clarity — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/02. Series 02 - The Execution Mindset/Stop_Discussion_Start_Action_Through_Clarity.m4a'
),
-- Execution Mindset episode 9: Cutting the Noise (alternate recordings)
(
  'cutting-the-noise-focus-habits-alt',
  'Cutting the Noise - Focus Habits for Digital Workers',
  'Thought Leadership',
  '2025-01-18',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'An additional recording of "Cutting the Noise - Focus Habits for Digital Workers" for digital workers who want more options for how they listen and learn.',
  'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'People',
  ARRAY['podcast','execution mindset','focus','digital workers','series-2'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: cutting-the-noise-focus-habits-alt — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/02. Series 02 - The Execution Mindset/Cutting the Noise - Focus Habits for Digital Workers.m4a'
),
(
  'cutting-the-noise-focus-habits-alt-1',
  'Cutting the Noise - Focus Habits for Digital Workers (1)',
  'Thought Leadership',
  '2025-01-19',
  'DQ Leadership',
  'DQ Leadership',
  0,
  'Another alternate recording of "Cutting the Noise - Focus Habits for Digital Workers" so teams can choose the version that suits their context.',
  'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
  'DQ Leadership',
  NULL,
  'People',
  ARRAY['podcast','execution mindset','focus','digital workers','series-2'],
  '20+',
  'Company News',
  'DQ Leadership',
  'Culture & People',
  '# Episode: cutting-the-noise-focus-habits-alt-1 — see src/data/media/news.ts for full markdown content.',
  'Podcast',
  'DigitalQatalyst',
  '/02. Series 02 - The Execution Mindset/Cutting the Noise - Focus Habits for Digital Workers (1).m4a'
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  type = EXCLUDED.type,
  date = EXCLUDED.date,
  author = EXCLUDED.author,
  byline = EXCLUDED.byline,
  views = EXCLUDED.views,
  excerpt = EXCLUDED.excerpt,
  image = EXCLUDED.image,
  department = EXCLUDED.department,
  location = EXCLUDED.location,
  domain = EXCLUDED.domain,
  tags = EXCLUDED.tags,
  reading_time = EXCLUDED.reading_time,
  news_type = EXCLUDED.news_type,
  news_source = EXCLUDED.news_source,
  focus_area = EXCLUDED.focus_area,
  content = EXCLUDED.content,
  format = EXCLUDED.format,
  source = EXCLUDED.source,
  audio_url = EXCLUDED.audio_url,
  updated_at = NOW();

-- TODO: Add additional INSERT statements here for all podcast episodes (Action-Solver
-- and The Execution Mindset series) from src/data/media/news.ts.
