import { ServiceRequest } from "../../types";

export const mockServiceRequests: ServiceRequest[] = [
  {
    id: "sr-001",
    serviceName: "Laptop Keyboard Replacement",
    category: "IT Support",
    status: "approved",
    submittedDate: "2024-01-05T10:30:00Z",
    sla: 2,
    serviceProvider: "IT Support Desk",
    description: "The 'E' and 'R' keys are not responding consistently. Need a keyboard replacement or laptop repair.",
    requestedBy: {
      id: "user-123",
      name: "John Smith",
      email: "john.smith@company.com",
      department: "Engineering",
    },
    approvers: [
      {
        id: "user-456",
        name: "Sarah Johnson",
        role: "IT Lead",
        status: "approved",
        date: "2024-01-06T14:22:00Z",
        comments: "Approved for hardware repair/replacement.",
      },
    ],
  },
  {
    id: "sr-002",
    serviceName: "Annual Leave - 5 Days",
    category: "Leave Request",
    status: "under-review",
    submittedDate: "2024-01-08T09:15:00Z",
    sla: 3,
    serviceProvider: "HR & Department Manager",
    description: "Requesting annual leave from Jan 20th to Jan 24th for personal family vacation.",
    requestedBy: {
      id: "user-123",
      name: "John Smith",
      email: "john.smith@company.com",
      department: "Engineering",
    },
    approvers: [
      {
        id: "user-789",
        name: "Michael Wilson",
        role: "Department Head",
        status: "approved",
        date: "2024-01-09T11:05:00Z",
      },
    ],
  },
  {
    id: "sr-003",
    serviceName: "Figma Professional License",
    category: "Tool Request",
    status: "approved",
    submittedDate: "2024-01-02T14:45:00Z",
    sla: 5,
    serviceProvider: "Procurement",
    description: "Need Figma Professional license for upcoming product design phase.",
    requestedBy: {
      id: "user-123",
      name: "John Smith",
      email: "john.smith@company.com",
      department: "Product",
    },
  },
  {
    id: "sr-004",
    serviceName: "Software Access - Adobe Creative Cloud",
    category: "Tool Request",
    status: "rejected",
    submittedDate: "2023-12-15T11:20:00Z",
    serviceProvider: "Software Licensing",
    description: "Requesting access to Adobe CC suite for marketing asset creation.",
    requestedBy: {
      id: "user-123",
      name: "John Smith",
      email: "john.smith@company.com",
      department: "Marketing",
    },
    approvers: [
      {
        id: "user-901",
        name: "Patricia Garcia",
        role: "Department Lead",
        status: "rejected",
        date: "2023-12-16T16:30:00Z",
        comments: "License quota currently full. Please use Canva for basic needs or wait for Q1 allocation.",
      },
    ],
  },
  {
    id: "sr-005",
    serviceName: "Sick Leave - 1 Day",
    category: "Leave Request",
    status: "approved",
    submittedDate: "2023-12-10T08:00:00Z",
    sla: 1,
    serviceProvider: "HR",
    description: "Not feeling well today, taking a sick day.",
    requestedBy: {
      id: "user-123",
      name: "John Smith",
      email: "john.smith@company.com",
      department: "Engineering",
    },
  },
  {
    id: "sr-006",
    serviceName: "Access Card Not Working",
    category: "IT Support",
    status: "resolved",
    submittedDate: "2023-12-05T13:45:00Z",
    sla: 1,
    serviceProvider: "Facilities & IT",
    description: "My physical access card is not opening the main entrance door.",
    requestedBy: {
      id: "user-123",
      name: "John Smith",
      email: "john.smith@company.com",
      department: "Engineering",
    },
  },
  {
    id: "sr-007",
    serviceName: "External Monitor Request",
    category: "Tool Request",
    status: "draft",
    submittedDate: "2024-01-09T10:00:00Z",
    serviceProvider: "IT Logistics",
    description: "Requesting a secondary 27-inch monitor for development work.",
    requestedBy: {
      id: "user-123",
      name: "John Smith",
      email: "john.smith@company.com",
      department: "Engineering",
    },
  },
];

export const serviceCategories = [
  "IT Support",
  "Leave Request",
  "Tool Request"
];
