import GHCLanding from "./SixXDLandingLayout";
import type { LucideIcon } from "lucide-react";
import { Target, Brain, Layers, GitBranch, Users, BookOpen, Briefcase, GraduationCap } from "lucide-react";

const SIXXD_CARDS = [
  // Class 01 — Delivery Services (DBP)
  {
    id: "plant-4-0",
    number: 1,
    category: "Class 01 — Delivery Services (DBP)",
    title: "Plant 4.0",
    executionQuestion: "What: Industrial operations platform for connected, data-driven plants.",
    executionLens:
      "Why: Unifies performance, energy, automation, and OT security into one execution workspace.",
    route: "/marketplace/directory/products",
    icon: Layers as LucideIcon,
    gradient: "bg-gradient-to-br from-[#131e42] via-[#30478a] to-[#f0f6ff]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354686414-b937fd73-1454-446b-ba05-81a99e216fd2.jpg",
    ctaLabel: "Open Plant 4.0 →",
  },

  // Class 02 — Delivery Products (DT 2.0)
  {
    id: "dtmp",
    number: 2,
    category: "Class 02 — Delivery Products (DT2.0)",
    title: "DTMP",
    executionQuestion: "What: Bespoke DBP blueprints for managing transformation programmes.",
    executionLens: "Why: Keeps portfolio, analytics, governance, and delivery aligned in one system.",
    route: "/marketplace/directory/products",
    icon: Target as LucideIcon,
    gradient: "bg-gradient-to-br from-[#131e42] via-[#1d2f64] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354560794-72c7a866-573c-455f-ac74-44c6753068f5.jpg",
    ctaLabel: "Open DTMP →",
  },
  {
    id: "tmaas",
    number: 3,
    category: "Class 02 — Delivery Products (DT2.0)",
    title: "TMaaS",
    executionQuestion: "What: Marketplace of on-demand transformation initiatives and accelerators.",
    executionLens: "Why: Standardises how teams start and scale delivery with repeatable playbooks.",
    route: "/marketplace/directory/products",
    icon: Briefcase as LucideIcon,
    gradient: "bg-gradient-to-br from-[#1b2553] via-[#243a75] to-[#e1513b]",
    accent: "#f0f6ff",
    image:
      "https://image2url.com/r2/default/images/1770711252171-5234c11d-afc2-44ba-a4f6-30269cd2bd3b.png",
    ctaLabel: "Open TMaaS →",
  },
  {
    id: "dto4t",
    number: 4,
    category: "Class 02 — Delivery Products (DT2.0)",
    title: "DTO4T",
    executionQuestion: "What: AI-driven transformation clinic that diagnoses maturity and prescribes initiatives.",
    executionLens: "Why: Makes transformation faster, cheaper, and more repeatable using data-driven pathways.",
    route: "/marketplace/directory/products",
    icon: GitBranch as LucideIcon,
    gradient: "bg-gradient-to-br from-[#131e42] via-[#1d2f64] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354729820-f4815c42-e9e5-4926-9d71-eb92bcc2b057.jpg",
    ctaLabel: "Open DTO4T →",
  },

  // Class 03 — Insight Products (DCO)
  {
    id: "dtmi",
    number: 5,
    category: "Class 03 — Insight Products (DCO)",
    title: "DTMI | DQ Web",
    executionQuestion: "What: Insight publishing platform for transformation knowledge and perspectives.",
    executionLens: "Why: Turns scattered content into structured intelligence for better decisions.",
    route: "/marketplace/directory/products",
    icon: Brain as LucideIcon,
    gradient: "bg-gradient-to-br from-[#1b2553] via-[#3f528e] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354705237-110f4c43-ac71-49be-b8a9-1a676146ecb6.jpg",
    ctaLabel: "Open DTMI →",
  },
  {
    id: "dtma",
    number: 6,
    category: "Class 03 — Insight Products (DCO)",
    title: "DTMA",
    executionQuestion: "What: Digital Transformation Management Academy with practice-based learning.",
    executionLens: "Why: Builds role-relevant capability without slowing delivery.",
    route: "/marketplace/directory/products",
    icon: GraduationCap as LucideIcon,
    gradient: "bg-gradient-to-br from-[#1b2553] via-[#243a75] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354661040-ec3eb531-5010-4f68-8897-a5501623bfc3.jpg",
    ctaLabel: "Open DTMA →",
  },
  {
    id: "dtmb",
    number: 7,
    category: "Class 03 — Insight Products (DCO)",
    title: "DTMB (6xD)",
    executionQuestion: "What: Book-based playbooks for Agile 6xD execution.",
    executionLens: "Why: Keeps teams executing with the same discipline and language.",
    route: "/marketplace/directory/products",
    icon: BookOpen as LucideIcon,
    gradient: "bg-gradient-to-br from-[#1b2553] via-[#243a75] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354752481-f1a62033-22f9-483a-ba44-f24b95c2a535.jpg",
    ctaLabel: "Open DTMB (6xD) →",
  },
  {
    id: "dtmc",
    number: 8,
    category: "Class 03 — Insight Products (DCO)",
    title: "DTMC (GHC)",
    executionQuestion: "What: Book-based playbooks for the GHC competency system.",
    executionLens: "Why: Protects alignment across culture, governance, and execution at scale.",
    route: "/marketplace/directory/products",
    icon: BookOpen as LucideIcon,
    gradient: "bg-gradient-to-br from-[#1b2553] via-[#243a75] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354752481-f1a62033-22f9-483a-ba44-f24b95c2a535.jpg",
    ctaLabel: "Open DTMC (GHC) →",
  },

  // Class 04 — Transaction Platforms (TxM)
  {
    id: "txm",
    number: 9,
    category: "Class 04 — Transaction Platforms (TxM)",
    title: "TxM (B2B2C)",
    executionQuestion: "What: Transaction platform for consumer and experience ecosystems.",
    executionLens: "Why: Makes execution scalable across high-volume journeys and service interactions.",
    route: "/marketplace/directory/products",
    icon: Layers as LucideIcon,
    gradient: "bg-gradient-to-br from-[#131e42] via-[#1d2f64] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354729820-f4815c42-e9e5-4926-9d71-eb92bcc2b057.jpg",
    ctaLabel: "Open TxM (B2B2C) →",
  },
  {
    id: "txm-b2b2b",
    number: 10,
    category: "Class 04 — Transaction Platforms (TxM)",
    title: "TxM (B2B2B)",
    executionQuestion: "What: Transaction platform for transformation and enterprise ecosystems.",
    executionLens: "Why: Standardises handoffs and execution across partners, teams, and enterprise workflows.",
    route: "/marketplace/directory/products",
    icon: Layers as LucideIcon,
    gradient: "bg-gradient-to-br from-[#131e42] via-[#1d2f64] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354729820-f4815c42-e9e5-4926-9d71-eb92bcc2b057.jpg",
    ctaLabel: "Open TxM (B2B2B) →",
  },
];

const SIXXD_FEATURES = [
  {
    title: "Designed for Reality",
    description: "Agile 6xD was built to handle shifting priorities, complexity, and continuous change.",
    icon: Target,
  },
  {
    title: "Built to Scale",
    description: "Transformation is structured as a system — not pilots that stall.",
    icon: Layers,
  },
  {
    title: "Six Connected Perspectives",
    description: "Each perspective answers a critical question organisations must face to stay relevant.",
    icon: GitBranch,
  },
];

const SIXXD_ACTIONS = [
  {
    title: "Learn by doing",
    icon: GraduationCap,
    badge: "Start here",
    description: "New joiners: build delivery habits fast through missions that mirror DQ execution.",
    tags: ["Practice", "Missions", "Feedback"],
    cta: "Start in Learning Center",
    path: "/lms?category=6xd",
    bg: "bg-[#e6ebff]",
    accent: "text-white",
    badgeColor: "text-white",
    iconColor: "#f0f6ff",
    variant: "primary",
  },
  {
    title: "Capability overview",
    icon: Layers,
    badge: "Understand",
    description: "Leaders and planners: understand the execution system before you act.",
    tags: ["Storybook", "Execution", "Context"],
    cta: "Read the Agile 6xD storybook",
    path: "/marketplace/guides/dq-6xd",
    bg: "bg-[#f0f6ff]",
    accent: "text-[#131e42]",
    badgeColor: "text-[#131e42]",
    iconColor: "#e1513b",
    variant: "secondary",
  },
  {
    title: "Product platforms",
    icon: BookOpen,
    badge: "Access",
    description: "Teams ready for live execution: move straight into the platforms used in delivery.",
    tags: ["DTMP", "DWS", "Plant 4.0"],
    cta: "Go to product platform ↗",
    path: "/marketplace/directory/products",
    bg: "bg-[#fde6de]",
    accent: "text-[#e1513b]",
    badgeColor: "text-[#e1513b]",
    iconColor: "#e1513b",
    variant: "secondary",
  },
];

export default function SixXDProductsLanding() {
  return (
    <GHCLanding
      badgeLabel="DQ Products"
      overrides={{
        heroHeadline: "Transformation fails when execution is fragmented.",
        heroHeadlineHighlightWord: "execution",
        heroHeadlineFontSize: "70px",
        heroSupporting: "DQ products exist to keep execution continuous, proven, and real.",
        heroCTA: "Read the Agile 6xD Storybook",
        heroCTALink: "/marketplace/guides/dq-6xd",
        heroFootnote: "Internal-first. Proven through real delivery.",
        foundationTitle: "What are DQ Products",
        foundationSubtitle:
          "Execution systems built from how DQ delivers. Used in live work before release. Only what survives real pressure ships. Designed to operate together as one system.",
        foundationTitleFontSize: "30px",
        foundationSubtitleFontSize: "16px",
        foundationCards: [
          {
            title: "Internal-First Execution",
            description: "Built inside DQ delivery teams and hardened on real deadlines.",
            icon: Target,
          },
          {
            title: "Delivery-Proven Systems",
            description: "Refined through real projects; if it fails in delivery, it never ships.",
            icon: Layers,
          },
          {
            title: "System, Not Tools",
            description: "Products operate together as one spine to prevent fragmentation.",
            icon: Layers,
          },
        ],
        foundationCTA: "Read the full Agile 6xD storybook",
        foundationCTATo: "/marketplace/guides/dq-6xd",
        foundationFootnote:
          "GHC shapes how we think; 6xD shapes how we execute; only delivery-proven systems become products.",
        responsesTitle: "DQ Products, grouped by execution class",
        responsesIntro:
          "Ten products. Four classes. One execution portfolio—built for real delivery.",
        responsesTitleFontSize: "30px",
        responsesIntroFontSize: "16px",
        responsesSequential: false,
        responsesLayout: "chips-grid",
        responseTags: [
          "All Products",
          "Class 01 — Delivery Services (DBP)",
          "Class 02 — Delivery Products (DT2.0)",
          "Class 03 — Insight Products (DCO)",
          "Class 04 — Transaction Platforms (TxM)",
        ],
        responseCards: SIXXD_CARDS,
        bottomCTA: "",
        actionCards: SIXXD_ACTIONS,
        finalHeadline: "Internal first. Delivery proven.",
        finalSubtitle:
          "We execute inside DQ first, release only after proof in delivery, and scale what works. Execution stays continuous, trusted, and repeatable.",
        finalCTALabel: "Read the Agile 6xD Storybook",
        finalCTATo: "/marketplace/guides/dq-6xd",
        finalCTASecondaryLabel: "Go to product platform ↗",
        finalCTASecondaryTo: "/marketplace/directory/products",
        finalHeadlineFontSize: "36px",
        takeActionTitleFontSize: "30px",
        takeActionSubtitleFontSize: "16px",
        takeActionTitle: "Choose your path",
        takeActionSubtitle:
          "Learn by doing, understand the system, or deploy platforms — pick the entry that matches your readiness and role.",
        takeActionLayout: "feature",
      }}
    />
  );
}
