import GHCLanding from "./SixXDLandingLayout";
import type { LucideIcon } from "lucide-react";
import { Target, Brain, Layers, GitBranch, Users, BookOpen, Briefcase, GraduationCap } from "lucide-react";

const SIXXD_CARDS = [
  {
    id: "dtmp",
    number: 1,
    category: "Digital Transformation Management Platform",
    title: "DTMP",
    executionQuestion: "Transformation work gets tracked after the fact instead of steered in real time.",
    executionLens:
      "For leaders and portfolio owners, DTMP unifies data, governance, and compliance so they can remove friction and accelerate delivery across initiatives.",
    story: "",
    problem: "",
    response: "",
    route: "/marketplace/guides/dq-agile-6xd",
    icon: Target as LucideIcon,
    gradient: "bg-gradient-to-br from-[#131e42] via-[#1d2f64] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354560794-72c7a866-573c-455f-ac74-44c6753068f5.jpg",
    ctaLabel: "Read capability overview",
  },
  {
    id: "dtma",
    number: 2,
    category: "Digital Transformation Management Academy",
    title: "DTMA",
    executionQuestion: "Teams are asked to transform without a shared practice.",
    executionLens:
      "For leaders and delivery teams, DTMA provides practice-driven learning paths that build skills applied directly to real work.",
    story: "",
    problem: "",
    response: "",
    route: "/marketplace/guides/dq-agile-6xd",
    icon: GraduationCap as LucideIcon,
    gradient: "bg-gradient-to-br from-[#1b2553] via-[#243a75] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354661040-ec3eb531-5010-4f68-8897-a5501623bfc3.jpg",
    ctaLabel: "Read capability overview",
  },
  {
    id: "dtmaas",
    number: 3,
    category: "Digital Transformation as a Service",
    title: "DTMaaS",
    executionQuestion: "Launching initiatives is slow and inconsistent across teams.",
    executionLens:
      "For transformation leads, DTMaaS offers a self-service marketplace of standard initiatives, templates, and accelerators so delivery starts faster and scales consistently.",
    story: "",
    problem: "",
    response: "",
    route: "/marketplace/guides/dq-agile-6xd",
    icon: Briefcase as LucideIcon,
    gradient: "bg-gradient-to-br from-[#131e42] via-[#30478a] to-[#f0f6ff]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354686414-b937fd73-1454-446b-ba05-81a99e216fd2.jpg",
    ctaLabel: "Read capability overview",
  },
  {
    id: "dtmi",
    number: 4,
    category: "Digital Transformation Management Insights",
    title: "DTMI",
    executionQuestion: "Transformation knowledge is scattered across documents and teams.",
    executionLens:
      "For decision makers and practitioners, DTMI curates insights into a live knowledge space that supports informed choices and alignment.",
    story: "",
    problem: "",
    response: "",
    route: "/marketplace/guides/dq-agile-6xd",
    icon: Brain as LucideIcon,
    gradient: "bg-gradient-to-br from-[#1b2553] via-[#3f528e] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354705237-110f4c43-ac71-49be-b8a9-1a676146ecb6.jpg",
    ctaLabel: "Read capability overview",
  },
  {
    id: "dto4t",
    number: 5,
    category: "Digital Twin of Organisation for Transformation",
    title: "DTO4T",
    executionQuestion: "Maturity and next steps are guessed instead of diagnosed.",
    executionLens:
      "For transformation teams, DTO4T uses data to assess maturity, prescribe actions, reduce risk, and speed time-to-value.",
    story: "",
    problem: "",
    response: "",
    route: "/marketplace/guides/dq-agile-6xd",
    icon: GitBranch as LucideIcon,
    gradient: "bg-gradient-to-br from-[#131e42] via-[#1d2f64] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354729820-f4815c42-e9e5-4926-9d71-eb92bcc2b057.jpg",
    ctaLabel: "Read capability overview",
  },
  {
    id: "dtmb",
    number: 6,
    category: "Digital Transformation Management Book",
    title: "DTMB",
    executionQuestion: "Transformation guidance varies by team and gets interpreted differently.",
    executionLens:
      "For leaders and practitioners, DTMB translates transformation into practical models that guide design, steering, and sustainment.",
    story: "",
    problem: "",
    response: "",
    route: "/marketplace/guides/dq-agile-6xd",
    icon: BookOpen as LucideIcon,
    gradient: "bg-gradient-to-br from-[#1b2553] via-[#243a75] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354752481-f1a62033-22f9-483a-ba44-f24b95c2a535.jpg",
    ctaLabel: "Read capability overview",
  },
  {
    id: "plant-4-0",
    number: 7,
    category: "Digital Cognitive Plant Platform",
    title: "Plant 4.0",
    executionQuestion: "Industrial execution is fragmented across assets, systems, and sites.",
    executionLens:
      "For industrial operators and engineers, Plant 4.0 connects assets, performance, energy, automation, and security so teams run with clarity and control across sites.",
    story: "",
    problem: "",
    response: "",
    route: "/marketplace/guides/dq-agile-6xd",
    icon: Layers as LucideIcon,
    gradient: "bg-gradient-to-br from-[#131e42] via-[#30478a] to-[#f0f6ff]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354686414-b937fd73-1454-446b-ba05-81a99e216fd2.jpg",
    ctaLabel: "Read capability overview",
  },
  {
    id: "dws",
    number: 8,
    category: "Digital Work Solution",
    title: "DWS",
    executionQuestion: "Execution slows when tools, services, and workflows live in different places.",
    executionLens:
      "For associates and delivery teams, DWS integrates collaboration, automation, and workspaces into one system that scales delivery without losing discipline.",
    story: "",
    problem: "",
    response: "",
    route: "/marketplace/guides/dq-agile-6xd",
    icon: Users as LucideIcon,
    gradient: "bg-gradient-to-br from-[#131e42] via-[#1d2f64] to-[#e1513b]",
    accent: "#f0f6ff",
    image: "https://image2url.com/r2/default/images/1770354729820-f4815c42-e9e5-4926-9d71-eb92bcc2b057.jpg",
    ctaLabel: "Read capability overview",
  },
];

const SIXXD_FEATURES = [
  {
    title: "Designed for Reality",
    description: "Agile 6xD was built to handle shifting priorities, complexity, and continuous change.",
    icon: Target,
  },
  {
    title: "Built to Scale",
    description: "Transformation is structured as a system — not pilots that stall.",
    icon: Layers,
  },
  {
    title: "Six Connected Perspectives",
    description: "Each perspective answers a critical question organisations must face to stay relevant.",
    icon: GitBranch,
  },
];

const SIXXD_ACTIONS = [
  {
    title: "Learn by doing",
    icon: GraduationCap,
    badge: "Start here",
    description: "Guided missions mirror how we execute inside DQ and help you build real delivery habits.",
    tags: ["Practice", "Missions", "Feedback"],
    cta: "Start in Learning Center",
    path: "/lms?category=6xd",
    bg: "bg-[#e6ebff]",
    accent: "text-white",
    badgeColor: "text-white",
    iconColor: "#f0f6ff",
    variant: "primary",
  },
  {
    title: "Capability overview",
    icon: Layers,
    badge: "Understand",
    description: "Read the Agile 6xD storybook to see the execution system behind the products.",
    tags: ["Storybook", "Execution", "Context"],
    cta: "Read the Agile 6xD storybook",
    path: "/marketplace/guides/dq-6xd",
    bg: "bg-[#f0f6ff]",
    accent: "text-[#131e42]",
    badgeColor: "text-[#131e42]",
    iconColor: "#e1513b",
    variant: "secondary",
  },
  {
    title: "Product platforms",
    icon: BookOpen,
    badge: "Access",
    description: "If you already know the system, go straight to the live platforms used in delivery.",
    tags: ["DTMP", "DWS", "Plant 4.0"],
    cta: "Go to product platform ↗",
    path: "/marketplace/directory/products",
    bg: "bg-[#fde6de]",
    accent: "text-[#e1513b]",
    badgeColor: "text-[#e1513b]",
    iconColor: "#e1513b",
    variant: "secondary",
  },
];

export default function SixXDProductsLanding() {
  return (
    <GHCLanding
      badgeLabel="The Agile 6xD"
      overrides={{
        heroHeadline: "Transformation fails when execution is fragmented.",
        heroHeadlineHighlightWord: "execution",
        heroHeadlineFontSize: "70px",
        heroSupporting:
          "Agile 6xD products are built from how we execute inside DQ. We prove them in real delivery before they become deployable systems.",
        heroCTA: "Read the Agile 6xD Storybook",
        heroCTALink: "/marketplace/guides/dq-6xd",
        heroFootnote: "Internal-first. Proven through real work.",
        foundationTitle: "What are Agile 6xD Products",
        foundationSubtitle:
          "Agile 6xD products are built from how we execute inside DQ. We prove them in real delivery before they become deployable systems.",
        foundationTitleFontSize: "30px",
        foundationSubtitleFontSize: "16px",
        foundationCards: [
          {
            title: "Internal-first execution",
            description:
              "We build and test these systems inside DQ teams before they leave our delivery environment.",
            icon: Target,
          },
          {
            title: "Built for real delivery",
            description:
              "Each product packages execution systems, delivery assets, and playbooks into formats teams can use with confidence.",
            icon: Layers,
          },
        ],
        foundationCTA: "Read the full Agile 6xD storybook",
        foundationCTATo: "/marketplace/guides/dq-6xd",
        foundationFootnote:
          "We apply Agile 6xD across real teams, platforms, and delivery environments first. Only what works under real conditions becomes a product.",
        responsesTitle: "Execution systems used at DQ",
        responsesIntro:
          "Each product solves a recurring execution problem and is built for the teams doing the work.",
        responsesTitleFontSize: "30px",
        responsesIntroFontSize: "16px",
        responsesSequential: true,
        responseTags: [
          "DTMP",
          "DTMA",
          "DTMaaS",
          "DTMI",
          "DTO4T",
          "DTMB",
          "Plant 4.0",
          "DWS",
        ],
        responseCards: SIXXD_CARDS,
        bottomCTA: "",
        actionCards: SIXXD_ACTIONS,
        finalHeadline: "Internal first. Delivery proven.",
        finalSubtitle:
          "We execute it inside DQ, refine it through real delivery, and only then release it as a product. That’s how transformation becomes practical, repeatable, and built for scale.",
        finalCTALabel: "Read the Agile 6xD Storybook",
        finalCTATo: "/marketplace/guides/dq-6xd",
        finalCTASecondaryLabel: "Go to product platform ↗",
        finalCTASecondaryTo: "/marketplace/directory/products",
        finalHeadlineFontSize: "36px",
        takeActionTitleFontSize: "30px",
        takeActionSubtitleFontSize: "16px",
        takeActionTitle: "Choose your path",
        takeActionSubtitle: "Get the context, then move into practice or go straight to the platforms.",
        takeActionLayout: "feature",
      }}
    />
  );
}
