// config/onboardingSteps.js
import {
  UserIcon,
  FileTextIcon,
  CreditCardIcon,
  HeartPulseIcon,
  PhoneIcon,
  UsersIcon,
  GraduationCapIcon,
  BriefcaseIcon,
  GlobeIcon,
  BuildingIcon,
  CheckIcon,
} from "lucide-react";
import { countries } from "../utils/countries";

export const onboardingSteps = [
  {
    id: "welcome",
    title: "Welcome",
    type: "welcome",
    icon: <BuildingIcon size={20} />,
  },
  {
    id: "professional-summary",
    title: "Professional Summary",
    type: "form",
    icon: <FileTextIcon size={20} />,
    sections: [
      {
        title: "Overview",
        description: "Brief professional biography and skills",
        fields: [
          {
            id: "bio",
            label: "Brief Bio",
            fieldName: "bio",
            required: true,
            type: "textarea",
            placeholder: "Tell us a bit about yourself...",
            minLength: 20,
          },
          {
            id: "hobbies",
            label: "Hobbies",
            fieldName: "hobbies",
            required: false,
            placeholder: "e.g., Reading, Hiking, Chess",
          },
          {
            id: "technicalSkills",
            label: "Technical Skills",
            fieldName: "technicalSkills",
            required: true,
            type: "textarea",
            placeholder: "List your technical skills...",
          },
          {
            id: "softSkills",
            label: "Soft Skills",
            fieldName: "softSkills",
            required: true,
            type: "textarea",
            placeholder: "e.g., Communication, Leadership...",
          },
          {
            id: "keyCompetencies",
            label: "Key Competencies",
            fieldName: "keyCompetencies",
            required: true,
            type: "textarea",
          },
          {
            id: "languages",
            label: "Languages",
            fieldName: "languages",
            required: true,
            placeholder: "e.g., English (Native), Arabic (Intermediate)",
          },
        ],
      },
    ],
  },
  {
    id: "profile-information",
    title: "Profile Information",
    type: "form",
    icon: <UserIcon size={20} />,
    sections: [
      {
        title: "Personal Details",
        fields: [
          {
            id: "dob",
            label: "Date of Birth",
            fieldName: "dob",
            required: true,
            type: "date",
          },
          {
            id: "gender",
            label: "Gender",
            fieldName: "gender",
            required: true,
            type: "select",
            options: [
              { value: "", label: "Select Gender" },
              { value: "male", label: "Male" },
              { value: "female", label: "Female" },
            ],
          },
          {
            id: "personalEmail",
            label: "Personal Email",
            fieldName: "personalEmail",
            required: true,
            type: "email",
          },
          {
            id: "maritalStatus",
            label: "Marital Status",
            fieldName: "maritalStatus",
            required: true,
            type: "select",
            options: [
              { value: "", label: "Select Status" },
              { value: "single", label: "Single" },
              { value: "married", label: "Married" },
              { value: "divorced", label: "Divorced" },
              { value: "widowed", label: "Widowed" },
            ],
          },
          {
            id: "numberOfChildren",
            label: "Number of Children",
            fieldName: "numberOfChildren",
            required: false,
            type: "number",
            min: 0,
          },
          {
            id: "numberOfDependants",
            label: "Number of Dependants",
            fieldName: "numberOfDependants",
            required: false,
            type: "number",
            min: 0,
          },
          {
            id: "homeAddress",
            label: "Address",
            fieldName: "homeAddress",
            required: true,
            type: "textarea",
          },
        ],
      },
    ],
  },
  {
    id: "identity-information",
    title: "Identity Information",
    type: "form",
    icon: <GlobeIcon size={20} />,
    sections: [
      {
        title: "Identification",
        fields: [
          {
            id: "countryOfResidence",
            label: "Country of Residence",
            fieldName: "countryOfResidence",
            required: true,
            type: "select",
            options: countries,
          },
          {
            id: "countryOfCitizenship",
            label: "Country of Citizenship",
            fieldName: "countryOfCitizenship",
            required: true,
            type: "select",
            options: countries,
          },
          {
            id: "nationalIdNumber",
            label: "National ID Number",
            fieldName: "nationalIdNumber",
            required: true,
          },
          {
            id: "passportNumber",
            label: "Passport Number",
            fieldName: "passportNumber",
            required: true,
          },
          {
            id: "passportExpiryDate",
            label: "Passport Expiry Date",
            fieldName: "passportExpiryDate",
            required: true,
            type: "date",
          },
          {
            id: "kraPin",
            label: "KRA Pin (NBO)",
            fieldName: "kraPin",
            required: true,
            applicableStudio: "NBO",
            helpText: "For Nairobi residents/citizens",
          },
        ],
      },
      {
        title: "UAE Visa Details (If Applicable)",
        applicableStudio: "DXB",
        fields: [
          {
            id: "emiratesIdNumber",
            label: "Emirates ID Number",
            fieldName: "emiratesIdNumber",
            required: true,
            applicableStudio: "DXB",
          },
          {
            id: "uaeVisaType",
            label: "UAE Visa Type",
            fieldName: "uaeVisaType",
            required: true,
            applicableStudio: "DXB",
            placeholder: "e.g., Employment, Golden Visa",
          },
          {
            id: "uaeVisaSponsor",
            label: "UAE Visa Sponsor",
            fieldName: "uaeVisaSponsor",
            required: false,
          },
          {
            id: "uaeVisaFileNumber",
            label: "UAE Visa File Number",
            fieldName: "uaeVisaFileNumber",
            required: false,
          },
          {
            id: "uaeVisaExpiryDate",
            label: "UAE Visa Expiry Date",
            fieldName: "uaeVisaExpiryDate",
            required: true,
            type: "date",
            applicableStudio: "DXB",
          },
        ],
      },
    ],
  },
  {
    id: "education",
    title: "Education Information",
    type: "form",
    icon: <GraduationCapIcon size={20} />,
    sections: [
      {
        title: "Academic Background",
        fields: [
          {
            id: "highestEducationLevel",
            label: "Highest Education Level",
            fieldName: "highestEducationLevel",
            required: true,
            type: "select",
            options: [
              { value: "", label: "Select Level" },
              { value: "highSchool", label: "High School" },
              { value: "diploma", label: "Diploma" },
              { value: "bachelors", label: "Bachelor's Degree" },
              { value: "masters", label: "Master's Degree" },
              { value: "phd", label: "PhD" },
              { value: "other", label: "Other" },
            ],
          },
          {
            id: "degreeAttained",
            label: "Degree/Certificate Attained",
            fieldName: "degreeAttained",
            required: true,
          },
          {
            id: "majorStudy",
            label: "Major/Area of Study",
            fieldName: "majorStudy",
            required: true,
          },
        ],
      },
      {
        title: "Systems Proficiency",
        fields: [
          {
            id: "toolsSystemProficiency",
            label: "Tools and System Proficiency",
            fieldName: "toolsSystemProficiency",
            required: true,
            type: "textarea",
            placeholder: "List software, tools, and systems you are proficient in",
            helpText: "e.g., Jira, Salesforce, Adobe Suite, Python, etc.",
          },
        ],
      },
      {
        title: "Further Studies",
        fields: [
          {
            id: "furtherStudyAspirations",
            label: "Further Study Aspirations",
            fieldName: "furtherStudyAspirations",
            type: "textarea",
            required: false,
          },
          {
            id: "furtherStudyTimeframe",
            label: "Further Study Timeframe",
            fieldName: "furtherStudyTimeframe",
            required: false,
          },
          {
            id: "furtherStudyStatus",
            label: "Further Study Status",
            fieldName: "furtherStudyStatus",
            required: false,
            type: "select",
            options: [
              { value: "", label: "Select Status" },
              { value: "planning", label: "Planning" },
              { value: "enrolled", label: "Enrolled" },
              { value: "deferred", label: "Deferred" },
            ],
          },
          {
            id: "interestedUpskilling",
            label: "Interested Areas of Upskilling",
            fieldName: "interestedUpskilling",
            required: false,
            type: "textarea",
          },
        ],
      },
    ],
  },
  {
    id: "work-experience",
    title: "Work Experience",
    type: "form",
    icon: <BriefcaseIcon size={20} />,
    sections: [
      {
        title: "Experience",
        fields: [
          {
            id: "yearsExperience",
            label: "Number of Years",
            fieldName: "yearsExperience",
            required: true,
            type: "number",
            min: 0,
          },
          {
            id: "skills",
            label: "Skills",
            fieldName: "skills",
            required: true,
            type: "repeater",
            placeholder: "e.g., React, Project Management, Writing",
          },
        ],
      },
    ],
  },
  {
    id: "payroll",
    title: "Payroll Information",
    type: "form",
    icon: <CreditCardIcon size={20} />,
    sections: [
      {
        title: "Bank Details",
        fields: [
          {
            id: "bankAccountName",
            label: "Name as per Bank Account",
            fieldName: "bankAccountName",
            required: true,
          },
          {
            id: "bankName",
            label: "Bank Name",
            fieldName: "bankName",
            required: true,
          },
          {
            id: "bankAddress",
            label: "Bank Address",
            fieldName: "bankAddress",
            required: true,
          },
          {
            id: "bankAccountNumber",
            label: "Bank Account Number",
            fieldName: "bankAccountNumber",
            required: true,
          },
          {
            id: "iban",
            label: "IBAN",
            fieldName: "iban",
            required: false,
          },
          {
            id: "swiftCode",
            label: "SWIFT Code",
            fieldName: "swiftCode",
            required: true,
          },
        ],
      },
      {
        title: "Mpesa Details (NBO)",
        applicableStudio: "NBO",
        fields: [
          {
            id: "mpesaAccountName",
            label: "Mpesa Account Name",
            fieldName: "mpesaAccountName",
            required: true,
            applicableStudio: "NBO",
          },
          {
            id: "mpesaAccountNumber",
            label: "Mpesa Account Number",
            fieldName: "mpesaAccountNumber",
            required: true,
            applicableStudio: "NBO",
          },
        ],
      },
    ],
  },
  {
    id: "health",
    title: "Health Information",
    type: "form",
    icon: <HeartPulseIcon size={20} />,
    sections: [
      {
        title: "Medical Details",
        fields: [
          {
            id: "allergies",
            label: "Known Allergies",
            fieldName: "allergies",
            required: false,
            type: "textarea",
            placeholder: "List any known allergies or type 'None'",
          },
          {
            id: "medicalConditions",
            label: "Known Medical Conditions",
            fieldName: "medicalConditions",
            required: false,
            type: "textarea",
          },
          {
            id: "currentMedications",
            label: "Current Medications",
            fieldName: "currentMedications",
            required: false,
            type: "textarea",
          },
          {
            id: "dietaryRestrictions",
            label: "Dietary Restrictions",
            fieldName: "dietaryRestrictions",
            required: false,
            type: "textarea",
          },
        ],
      },
    ],
  },
  {
    id: "emergency-contact",
    title: "Emergency Contact",
    type: "form",
    icon: <PhoneIcon size={20} />,
    sections: [
      {
        title: "Contact Details",
        fields: [
          {
            id: "emergencyName",
            label: "Name",
            fieldName: "emergencyName",
            required: true,
          },
          {
            id: "emergencyRelationship",
            label: "Relationship to Employee",
            fieldName: "emergencyRelationship",
            required: true,
          },
          {
            id: "emergencyPhone",
            label: "Phone Number",
            fieldName: "emergencyPhone",
            required: true,
            type: "tel",
          },
          {
            id: "emergencyEmail",
            label: "Email Address",
            fieldName: "emergencyEmail",
            required: false,
            type: "email",
          },
          {
            id: "emergencyAddress",
            label: "Address",
            fieldName: "emergencyAddress",
            required: true,
            type: "textarea",
          },
        ],
      },
    ],
  },
  {
    id: "referee",
    title: "Referee Information",
    type: "form",
    icon: <UsersIcon size={20} />,
    sections: [
      {
        title: "Reference",
        fields: [
          {
            id: "referees",
            label: "Referees",
            fieldName: "referees",
            required: true,
            type: "repeater",
            itemTemplate: [
              { fieldName: "name", label: "Name", required: true },
              { fieldName: "organization", label: "Organization", required: true },
              { fieldName: "position", label: "Position", required: true },
              { fieldName: "phone", label: "Phone", required: true, type: "tel" },
              { fieldName: "email", label: "Email", required: true, type: "email" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "review",
    title: "Review",
    type: "review",
    icon: <CheckIcon size={20} />,
  },
];

