// Mock data for Knowledge Hub marketplace
export const mockKnowledgeHubItems = [
  {
    id: '1',
    title: 'Abu Dhabi SME Growth Strategies',
    description:
      'Comprehensive guide to scaling your business in Abu Dhabi with practical insights and local market analysis.',
    mediaType: 'Guide',
    businessStage: 'Growth',
    domain: 'Strategy & Growth',
    format: 'In-Depth Reports',
    popularity: 'Trending',
    provider: {
      name: 'Digital Qatalyst',
      logoUrl: '/DWS-Logo.png',
      description: 'Supporting entrepreneurs and SMEs in Abu Dhabi.',
    },
    tags: ['Strategy', 'Growth'],
    imageUrl:
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'May 15, 2023',
    downloadCount: 1253,
    fileSize: '4.2 MB',
  },
  {
    id: '2',
    title: 'Digital Transformation for SMEs',
    description:
      'Learn how to leverage digital technologies to transform your business operations and customer experience.',
    mediaType: 'Report',
    businessStage: 'Established',
    domain: 'Technology & Innovation',
    format: 'In-Depth Reports',
    popularity: 'Most Downloaded',
    provider: {
      name: 'Hub71',
      logoUrl: 'https://hub71.com/wp-content/uploads/2023/05/hub71-logo-1.png',
      description: "Abu Dhabi's global tech ecosystem for startups.",
    },
    tags: ['Technology', 'Digital'],
    imageUrl:
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'April 28, 2023',
    downloadCount: 2845,
    fileSize: '5.8 MB',
  },
  {
    id: '3',
    title: 'Funding Options for Abu Dhabi Startups',
    description:
      'Explore various funding options available for startups in Abu Dhabi, from venture capital to government grants.',
    mediaType: 'Guide',
    businessStage: 'Startup',
    domain: 'Finance & Funding',
    format: 'Quick Reads',
    popularity: "Editor's Pick",
    provider: {
      name: 'ADGM Academy',
      logoUrl:
        'https://images.squarespace-cdn.com/content/v1/5cc0e1e9a0cd27177a2dd7ec/1556171141973-2BKLJ7QWZM0RN9Y1DKBY/ADGM+Academy.png',
      description: 'The knowledge arm of Abu Dhabi Global Market.',
    },
    tags: ['Finance', 'Funding'],
    imageUrl:
      'https://images.unsplash.com/photo-1559526324-593bc073d938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'March 15, 2023',
    downloadCount: 1876,
    fileSize: '3.5 MB',
  },
  {
    id: '4',
    title: 'Financial Planning Templates',
    description:
      'Ready-to-use templates for financial planning and forecasting with automated calculations and projections.',
    mediaType: 'Toolkits & Templates',
    businessStage: 'Idea Stage',
    domain: 'Finance & Funding',
    format: 'Downloadable Templates',
    popularity: 'Most Downloaded',
    provider: {
      name: 'NYU Abu Dhabi',
      logoUrl:
        'https://nyuad.nyu.edu/content/dam/nyuad/departments/public-affairs/logos/NYUAD-logo-color.png',
      description:
        'A degree-granting research university with a liberal arts and science college.',
    },
    tags: ['Finance', 'Templates'],
    imageUrl:
      'https://images.unsplash.com/photo-1554224155-6726b3ff858f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'February 10, 2023',
    downloadCount: 3254,
    fileSize: '1.8 MB',
  },
  {
    id: '5',
    title: 'Abu Dhabi Business Forum 2023',
    description:
      'Join the largest business networking event in Abu Dhabi with industry leaders and government officials.',
    mediaType: 'Event',
    businessStage: 'All Stages',
    domain: 'Strategy & Growth',
    format: 'Live Events',
    popularity: 'Latest',
    provider: {
      name: 'Abu Dhabi Chamber of Commerce',
      logoUrl:
        'https://upload.wikimedia.org/wikipedia/en/0/08/Abu_Dhabi_Chamber_Logo.png',
      description:
        'Supporting business growth and economic development in Abu Dhabi.',
    },
    tags: ['Event', 'Networking'],
    imageUrl:
      'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'June 15-16, 2023',
    location: 'Abu Dhabi National Exhibition Centre',
  },
  {
    id: '6',
    title: 'Marketing Strategy for SMEs',
    description:
      'Learn effective marketing strategies tailored for small and medium enterprises in the UAE market.',
    mediaType: 'Video',
    businessStage: 'Growth',
    domain: 'Marketing & Sales',
    format: 'Recorded Media',
    popularity: 'Trending',
    provider: {
      name: 'Google for Startups',
      logoUrl:
        'https://storage.googleapis.com/cms-storage-bucket/6e19fee6b47b36ca613f.png',
      description:
        "Google's program to help startups thrive across every corner of the world.",
    },
    tags: ['Marketing', 'Strategy'],
    imageUrl:
      'https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'April 5, 2023',
    duration: '45 minutes',
  },
  {
    id: '7',
    title: 'Legal Compliance Guide for UAE Businesses',
    description:
      'Essential guide to understanding and complying with UAE business regulations and legal requirements.',
    mediaType: 'Guide',
    businessStage: 'All Stages',
    domain: 'Legal & Compliance',
    format: 'In-Depth Reports',
    popularity: 'Most Downloaded',
    provider: {
      name: 'ADGM Academy',
      logoUrl:
        'https://images.squarespace-cdn.com/content/v1/5cc0e1e9a0cd27177a2dd7ec/1556171141973-2BKLJ7QWZM0RN9Y1DKBY/ADGM+Academy.png',
      description: 'The knowledge arm of Abu Dhabi Global Market.',
    },
    tags: ['Legal', 'Compliance'],
    imageUrl:
      'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'January 20, 2023',
    downloadCount: 2156,
    fileSize: '6.2 MB',
  },
  {
    id: '8',
    title: 'Operational Excellence Podcast',
    description:
      'Weekly podcast discussing operational best practices for businesses in the UAE and wider Middle East.',
    mediaType: 'Podcast',
    businessStage: 'Established',
    domain: 'Operations & Productivity',
    format: 'Recorded Media',
    popularity: 'Latest',
    provider: {
      name: 'Digital Qatalyst',
      logoUrl: '/DWS-Logo.png',
      description: 'Supporting entrepreneurs and SMEs in Abu Dhabi.',
    },
    tags: ['Operations', 'Productivity'],
    imageUrl:
      'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'May 5, 2023',
    duration: '30 minutes',
    episodes: 25,
  },
  {
    id: '9',
    title: 'Innovation Workshop Series',
    description:
      'Interactive workshop series focused on fostering innovation and creative problem-solving in your business.',
    mediaType: 'Event',
    businessStage: 'Growth',
    domain: 'Technology & Innovation',
    format: 'Live Events',
    popularity: "Editor's Pick",
    provider: {
      name: 'Hub71',
      logoUrl: 'https://hub71.com/wp-content/uploads/2023/05/hub71-logo-1.png',
      description: "Abu Dhabi's global tech ecosystem for startups.",
    },
    tags: ['Innovation', 'Workshop'],
    imageUrl:
      'https://images.unsplash.com/photo-1540317580384-e5d43867caa6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'June 5-7, 2023',
    location: 'Hub71, Abu Dhabi',
  },
  {
    id: '10',
    title: 'Business Plan Templates',
    description:
      'Comprehensive templates to help you create a professional business plan for your startup or growth-stage business.',
    mediaType: 'Toolkits & Templates',
    businessStage: 'Idea Stage',
    domain: 'Strategy & Growth',
    format: 'Downloadable Templates',
    popularity: 'Most Downloaded',
    provider: {
      name: 'Digital Qatalyst',
      logoUrl: '/DWS-Logo.png',
      description: 'Supporting entrepreneurs and SMEs in Abu Dhabi.',
    },
    tags: ['Business Plan', 'Templates'],
    imageUrl:
      'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'March 1, 2023',
    downloadCount: 4587,
    fileSize: '3.2 MB',
  },
  {
    id: '11',
    title: 'Export Market Analysis Report',
    description:
      'Detailed analysis of export opportunities for Abu Dhabi businesses with market insights and regulatory information.',
    mediaType: 'Report',
    businessStage: 'Scale-up',
    domain: 'Strategy & Growth',
    format: 'In-Depth Reports',
    popularity: 'Latest',
    provider: {
      name: 'Abu Dhabi Export Office',
      logoUrl: 'https://www.adexporters.ae/sites/default/files/adex-logo.png',
      description:
        'Supporting Abu Dhabi-based companies to export their products globally.',
    },
    tags: ['Export', 'Market Research'],
    imageUrl:
      'https://images.unsplash.com/photo-1493894473891-10fc1e5dbd22?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1469&q=80',
    date: 'April 18, 2023',
    downloadCount: 1456,
    fileSize: '7.5 MB',
  },
  {
    id: '12',
    title: 'Tech Startups in Abu Dhabi See 40% Growth',
    description:
      'Technology startups in Abu Dhabi have seen a 40% growth in the past year, according to a new report.',
    mediaType: 'News',
    businessStage: 'Startup',
    domain: 'Technology & Innovation',
    format: 'Quick Reads',
    popularity: 'Trending',
    provider: {
      name: 'TechNews Daily',
      logoUrl: 'https://placehold.co/400x400/4338ca/white?text=TND',
      description: 'Leading technology news source in the UAE.',
    },
    tags: ['Technology', 'Startup'],
    imageUrl:
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    date: 'April 28, 2023',
  },
]

// Mock data for Knowledge Hub filter options
export const mockKnowledgeHubFilterOptions = {
  mediaTypes: [
    { id: 'news', name: 'News' },
    { id: 'reports', name: 'Reports' },
    { id: 'toolkits', name: 'Toolkits & Templates' },
    { id: 'guides', name: 'Guides' },
    { id: 'events', name: 'Events' },
    { id: 'videos', name: 'Videos' },
    { id: 'podcasts', name: 'Podcasts' },
  ],
  businessStages: [
    { id: 'idea', name: 'Idea Stage' },
    { id: 'startup', name: 'Startup' },
    { id: 'growth', name: 'Growth' },
    { id: 'scaleup', name: 'Scale-up' },
    { id: 'established', name: 'Established' },
  ],
  domains: [
    { id: 'finance', name: 'Finance & Funding' },
    { id: 'marketing', name: 'Marketing & Sales' },
    { id: 'technology', name: 'Technology & Innovation' },
    { id: 'operations', name: 'Operations & Productivity' },
    { id: 'legal', name: 'Legal & Compliance' },
    { id: 'strategy', name: 'Strategy & Growth' },
  ],
  formats: [
    { id: 'quickreads', name: 'Quick Reads' },
    { id: 'indepth', name: 'In-Depth Reports' },
    { id: 'interactive', name: 'Interactive Tools' },
    { id: 'templates', name: 'Downloadable Templates' },
    { id: 'recorded', name: 'Recorded Media' },
    { id: 'live', name: 'Live Events' },
  ],
  popularity: [
    { id: 'latest', name: 'Latest' },
    { id: 'trending', name: 'Trending' },
    { id: 'downloaded', name: 'Most Downloaded' },
    { id: 'editors', name: "Editor's Pick" },
  ],
}

// Mock data for financial services
export const mockFinancialServices = [
  {
    id: 'fin-1',
    title: 'SME Growth Loan',
    description:
      'Low-interest loans designed specifically for small and medium enterprises looking to expand their operations in Abu Dhabi.',
    category: 'Loans',
    serviceType: 'Financing',
    businessStage: 'Growth',
    provider: {
      name: 'Abu Dhabi Commercial Bank',
      logoUrl:
        'https://upload.wikimedia.org/wikipedia/commons/8/80/ADCB_Logo.svg',
      description:
        'One of the largest banks in the UAE, offering a wide range of financial services for businesses.',
    },
    amount: 'Up to AED 5 million',
    duration: '5-7 years',
    interestRate: 'Starting from 3%',
    eligibility:
      'Business must be operating for at least 2 years with annual revenue of AED 1 million+',
    details: [
      'No collateral required for loans up to AED 1 million',
      'Flexible repayment options',
      'Dedicated relationship manager',
      'Fast approval process within 5 business days',
      'Option for grace period of up to 6 months',
    ],
    tags: ['Loans', 'Financing', 'Growth'],
  },
  {
    id: 'fin-2',
    title: 'Startup Capital Fund',
    description:
      'Equity financing for innovative startups in technology, healthcare, and sustainable energy sectors in Abu Dhabi.',
    category: 'Financing',
    serviceType: 'Equity',
    businessStage: 'Conception',
    provider: {
      name: 'Hub71',
      logoUrl: 'https://hub71.com/wp-content/uploads/2023/05/hub71-logo-1.png',
      description:
        "Abu Dhabi's global tech ecosystem that enables startups to scale globally.",
    },
    amount: 'AED 500,000 - 2 million',
    duration: 'Equity investment',
    interestRate: 'N/A (Equity-based)',
    eligibility:
      'Innovative startups with strong growth potential in priority sectors',
    details: [
      'Equity investment ranging from 10-25%',
      "Access to Hub71's ecosystem and mentorship",
      'Connection to potential clients and partners',
      'Support with future funding rounds',
      'No repayment obligations',
    ],
    tags: ['Financing', 'Equity', 'Conception'],
  },
  {
    id: 'fin-3',
    title: 'Business Insurance Package',
    description:
      'Comprehensive insurance coverage tailored for businesses operating in Abu Dhabi, protecting against various risks.',
    category: 'Insurance',
    serviceType: 'Risk Management',
    businessStage: 'All Stages',
    provider: {
      name: 'Abu Dhabi National Insurance Company',
      logoUrl:
        'https://www.adnic.ae/wp-content/themes/adnic/assets/images/logo.svg',
      description:
        'Leading insurance provider in the UAE offering comprehensive coverage for businesses.',
    },
    amount: 'Coverage up to AED 10 million',
    duration: 'Annual, renewable',
    interestRate: 'N/A',
    eligibility: 'Licensed businesses operating in Abu Dhabi',
    details: [
      'Property and asset protection',
      'Business interruption coverage',
      'Liability insurance',
      'Employee health and accident coverage',
      'Customizable package based on business needs',
    ],
    tags: ['Insurance', 'Risk Management', 'All Stages'],
  },
  {
    id: 'fin-4',
    title: 'Export Credit Guarantee',
    description:
      'Financial protection for Abu Dhabi businesses engaged in export activities, minimizing risks of international trade.',
    category: 'Insurance',
    serviceType: 'Credit',
    businessStage: 'Maturity',
    provider: {
      name: 'Abu Dhabi Exports Office',
      logoUrl: 'https://www.adexporters.ae/sites/default/files/adex-logo.png',
      description:
        'Government entity supporting Abu Dhabi-based exporters to expand globally.',
    },
    amount: 'Up to 90% of export value',
    duration: 'Transaction-based',
    interestRate: 'N/A',
    eligibility: 'Abu Dhabi-based companies with export activities',
    details: [
      'Protection against non-payment by international buyers',
      'Coverage for commercial and political risks',
      'Improved cash flow management',
      'Enhanced credibility with international partners',
      'Access to competitive financing terms',
    ],
    tags: ['Insurance', 'Credit', 'Maturity'],
  },
  {
    id: 'fin-5',
    title: 'Business Credit Card',
    description:
      'Specialized credit card for business expenses with rewards tailored to business needs and spending patterns.',
    category: 'Credit Card',
    serviceType: 'Credit',
    businessStage: 'All Stages',
    provider: {
      name: 'First Abu Dhabi Bank',
      logoUrl:
        'https://www.bankfab.com/-/media/fabgroup/home/images/fab-logo.svg',
      description:
        'The largest bank in the UAE, offering comprehensive financial services for businesses of all sizes.',
    },
    amount: 'Credit limit up to AED 500,000',
    duration: 'Revolving credit',
    interestRate: '18% APR',
    eligibility: 'Registered businesses with good credit history',
    details: [
      'Business-specific rewards and cashback',
      'Multiple cards for employees with spending controls',
      'Detailed expense reporting and categorization',
      'Travel insurance and purchase protection',
      'Integration with accounting software',
    ],
    tags: ['Credit Card', 'Credit', 'All Stages'],
  },
  {
    id: 'fin-6',
    title: 'Equipment Financing',
    description:
      'Specialized financing solution for purchasing business equipment and machinery with flexible terms.',
    category: 'Loans',
    serviceType: 'Financing',
    businessStage: 'Growth',
    provider: {
      name: 'Abu Dhabi Islamic Bank',
      logoUrl: 'https://www.adib.ae/en/PublishingImages/ADIB_Logo_2016_En.svg',
      description:
        'Leading Islamic financial services group providing Sharia-compliant solutions for businesses.',
    },
    amount: 'Up to AED 3 million',
    duration: '3-5 years',
    interestRate: 'Profit rate from 4%',
    eligibility: 'Business must be operating for at least 1 year',
    details: [
      'Sharia-compliant financing structure',
      'Equipment serves as collateral',
      'Flexible payment schedules',
      'Option to purchase equipment at end of term',
      'Quick approval process',
    ],
    tags: ['Loans', 'Financing', 'Growth'],
  },
  {
    id: 'fin-7',
    title: 'Working Capital Solution',
    description:
      'Short-term financing to optimize cash flow and cover operational expenses during growth or seasonal fluctuations.',
    category: 'Financing',
    serviceType: 'Credit',
    businessStage: 'Growth',
    provider: {
      name: 'Abu Dhabi Commercial Bank',
      logoUrl:
        'https://upload.wikimedia.org/wikipedia/commons/8/80/ADCB_Logo.svg',
      description:
        'One of the largest banks in the UAE, offering a wide range of financial services for businesses.',
    },
    amount: 'AED 250,000 - 3 million',
    duration: '6-12 months',
    interestRate: 'Starting from 4.5%',
    eligibility: 'Businesses with at least 18 months of operation',
    details: [
      'Revolving credit facility',
      'Flexible withdrawal and repayment',
      'Online account management',
      'No prepayment penalties',
      'Competitive interest rates',
    ],
    tags: ['Financing', 'Credit', 'Growth'],
  },
  {
    id: 'fin-8',
    title: 'Trade Finance Facility',
    description:
      'Comprehensive trade finance solutions for businesses engaged in import and export activities.',
    category: 'Financing',
    serviceType: 'Credit',
    businessStage: 'Maturity',
    provider: {
      name: 'First Abu Dhabi Bank',
      logoUrl:
        'https://www.bankfab.com/-/media/fabgroup/home/images/fab-logo.svg',
      description:
        'The largest bank in the UAE, offering comprehensive financial services for businesses of all sizes.',
    },
    amount: 'Up to AED 10 million',
    duration: 'Transaction-based',
    interestRate: 'Varies by product',
    eligibility: 'Established businesses with international trade activities',
    details: [
      'Letters of credit and guarantees',
      'Import and export financing',
      'Supply chain financing',
      'Documentary collections',
      'Trade risk mitigation',
    ],
    tags: ['Financing', 'Credit', 'Maturity'],
  },
  {
    id: 'fin-9',
    title: 'Business Restructuring Loan',
    description:
      'Specialized financing to support business transformation, debt consolidation, or operational restructuring.',
    category: 'Loans',
    serviceType: 'Financing',
    businessStage: 'Restructuring',
    provider: {
      name: 'Abu Dhabi Islamic Bank',
      logoUrl: 'https://www.adib.ae/en/PublishingImages/ADIB_Logo_2016_En.svg',
      description:
        'Leading Islamic financial services group providing Sharia-compliant solutions for businesses.',
    },
    amount: 'Up to AED 7 million',
    duration: 'Up to 10 years',
    interestRate: 'Profit rate from 3.5%',
    eligibility: 'Businesses with viable restructuring plan',
    details: [
      'Debt consolidation options',
      'Customized repayment schedule',
      'Business advisory services',
      'Grace period options',
      'Sharia-compliant structure',
    ],
    tags: ['Loans', 'Financing', 'Restructuring'],
  },
  {
    id: 'fin-10',
    title: 'Commercial Property Mortgage',
    description:
      'Long-term financing for purchasing commercial real estate or business premises in Abu Dhabi.',
    category: 'Loans',
    serviceType: 'Financing',
    businessStage: 'Maturity',
    provider: {
      name: 'First Abu Dhabi Bank',
      logoUrl:
        'https://www.bankfab.com/-/media/fabgroup/home/images/fab-logo.svg',
      description:
        'The largest bank in the UAE, offering comprehensive financial services for businesses of all sizes.',
    },
    amount: 'Up to AED 20 million',
    duration: 'Up to 15 years',
    interestRate: 'Starting from 3.75%',
    eligibility:
      'Businesses with strong financial performance and at least 3 years of operation',
    details: [
      'Up to 70% financing of property value',
      'Fixed and variable rate options',
      'Flexible repayment terms',
      'Option to refinance existing property',
      'No early settlement fees after 5 years',
    ],
    tags: ['Loans', 'Financing', 'Maturity'],
  },
  {
    id: 'fin-11',
    title: 'Invoice Factoring Service',
    description:
      'Convert outstanding invoices into immediate cash flow to support business operations and growth.',
    category: 'Financing',
    serviceType: 'Credit',
    businessStage: 'Growth',
    provider: {
      name: 'Abu Dhabi Commercial Bank',
      logoUrl:
        'https://upload.wikimedia.org/wikipedia/commons/8/80/ADCB_Logo.svg',
      description:
        'One of the largest banks in the UAE, offering a wide range of financial services for businesses.',
    },
    amount: 'Up to 85% of invoice value',
    duration: '30-90 days',
    interestRate: '2-3% monthly fee',
    eligibility: 'B2B businesses with creditworthy customers',
    details: [
      'Immediate access to working capital',
      'No additional debt on balance sheet',
      'Optional accounts receivable management',
      'Confidential and non-confidential options',
      'Online platform for invoice submission and tracking',
    ],
    tags: ['Financing', 'Credit', 'Growth'],
  },
  {
    id: 'fin-12',
    title: 'Green Business Financing',
    description:
      'Specialized financing for environmentally sustainable projects and business initiatives in Abu Dhabi.',
    category: 'Loans',
    serviceType: 'Financing',
    businessStage: 'All Stages',
    provider: {
      name: 'First Abu Dhabi Bank',
      logoUrl:
        'https://www.bankfab.com/-/media/fabgroup/home/images/fab-logo.svg',
      description:
        'The largest bank in the UAE, offering comprehensive financial services for businesses of all sizes.',
    },
    amount: 'Up to AED 15 million',
    duration: 'Up to 10 years',
    interestRate: 'Preferential rates from 2.5%',
    eligibility: 'Projects with demonstrable environmental benefits',
    details: [
      'Preferential interest rates',
      'Extended repayment periods',
      'Technical assistance for project development',
      'Compliance with international green standards',
      'Enhanced reputation through green certification',
    ],
    tags: ['Loans', 'Financing', 'All Stages'],
  },
]

// Mock data for non-financial services
export const mockNonFinancialServices = [
  {
    id: '1',
    title: 'IT Support Form',
    description:
      "Please use this form to submit any support requests related to Technology at DQ. Be sure to include details about the problem you're experiencing, along with any error messages you see. The more information you provide, the faster our support team can assist you.",
    category: 'Technology',
    serviceType: 'Support',
    deliveryMode: 'Hybrid',
    businessStage: 'All Stages',
    userCategory: ['Employee', 'Contractor', 'Manager'],
    technicalCategory: ['Hardware', 'Software', 'Network'],
    deviceOwnership: ['Company Device', 'Personal Device (BYOD)'],
    provider: {
      name: '',
      logoUrl: '/DWS-Logo.png',
      description:
        'DQ IT Support provides technical assistance and support for all technology-related issues and requests.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'Submit IT support requests efficiently',
      'Provide detailed problem descriptions',
      'Include relevant error messages',
      'Track support request progress',
      'Get timely assistance from our technical team',
    ],
    tags: [ 'Hybrid', 'Technology'],
    featuredImageUrl: '/images/services/IT-support.jpg',
    //requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
  },
  {
    id: '2',
    title: 'Support Charter Template',
    description:
      'Support Charter Template is a structured document that outlines the scope, responsibilities, standards, and expectations of the IT support function. It acts as a formal agreement or guideline between the IT support team and the users or departments they serve.',
    category: 'Technology',
    serviceType: 'Self-Service',
    deliveryMode: 'Hybrid',
    businessStage: 'All Stages',
    userCategory: ['Employee', 'Manager'],
    technicalCategory: ['Software'],
    deviceOwnership: ['Company Device'],
    provider: {
      name: 'IT Support',
      logoUrl: '/DWS-Logo.png',
      description:
        'DQ IT Support provides technical assistance and support for all technology-related issues and requests.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'Understand IT support scope and responsibilities',
      'Define service level agreements',
      'Establish support standards and expectations',
      'Create formal support agreements',
      'Access structured documentation templates',
    ],
    tags: ['Online', 'Technology'],
    featuredImageUrl: '/images/services/tech-support.jpg',
  },
  {
    id: '3',
    title: 'IT Support Walkthrough',
    description:
      'An instructional video detailing how to successfully launch an IT support request on the DWS platform.',
    category: 'Technology',
    serviceType: 'Self-Service',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    userCategory: ['Employee', 'Contractor', 'Intern'],
    technicalCategory: ['Software', 'Hardware'],
    deviceOwnership: ['Company Device', 'Personal Device (BYOD)'],
    provider: {
      name: 'IT Support',
      logoUrl: '/DWS-Logo.png',
      description:
        'DQ IT Support provides technical assistance and support for all technology-related issues and requests.',
    },
    duration: '5-10 minutes',
    price: 'Free',
    details: [
      'Navigate the DWS platform effectively',
      'Launch IT support requests correctly',
      'Follow proper request procedures',
      'Understand platform functionality',
      'Learn best practices for submitting requests',
    ],
    tags: ['IT Support', 'Online', 'Technology'],
    featuredImageUrl: '/images/services/IT_Support_Walkthrough.jpg',
  },
  {
    id: '10',
    title: 'Cursor AI',
    description:
      'Cursor AI is an advanced AI-powered code editor built on VS Code that transforms how developers write code. At DQ, we use Cursor to accelerate software development through intelligent code completion, natural language editing, and AI-assisted debugging, helping our teams ship features faster with fewer errors.',
    category: 'AI Tools',
    serviceType: 'Requisition',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    toolCategory: 'coding_ides',
    accessType: 'request_access',
    pricing: 'paid',
    provider: {
      name: 'Digital Innovation',
      logoUrl: '/DWS-Logo.png',
      description:
        'DQ Digital Innovation team manages AI tool provisioning, licensing, and onboarding for development teams.',
    },
    duration: '1-2 business days',
    price: 'Licensed',
    details: [
      'Submit Cursor AI access request',
      'Provide justification and use case',
      'Complete AI tool usage training',
      'Receive license and activation instructions',
      'Access to AI-powered coding assistance',
      'Integration with existing development workflow',
    ],
    tags: ['Digital Innovation', 'Online', 'AI Tools'],
    featuredImageUrl: '/images/services/cursor-ai.png',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=CursorAIRequest',
    homepageUrl: 'https://cursor.sh',
  },
  {
    id: '11',
    title: 'Lovable AI',
    description:
      'Lovable AI is an innovative low-code platform that uses AI to build full-stack web applications through natural language. DQ leverages Lovable for rapid prototyping and MVP development, enabling teams to validate ideas quickly and create production-ready web applications without extensive coding expertise.',
    category: 'AI Tools',
    serviceType: 'Requisition',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    toolCategory: 'low_code_tools',
    accessType: 'request_access',
    pricing: 'paid',
    provider: {
      name: 'Digital Innovation',
      logoUrl: '/Cursor-AI.png',
      description:
        'Digital Innovation team provides access to cutting-edge AI tools and low-code platforms for rapid application development.',
    },
    duration: '1-2 business days',
    price: 'Licensed',
    details: [
      'Request access to Lovable AI platform',
      'AI-powered low-code web app development',
      'Build full-stack applications with natural language',
      'Rapid prototyping and MVP creation',
      'Production-ready code generation',
      'Includes onboarding and usage guidelines',
    ],
    tags: ['Digital Innovation', 'Online', 'AI Tools'],
    featuredImageUrl: '/images/services/lovable-ai.jpg',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=LovableAIRequest',
    homepageUrl: 'https://lovable.dev',
  },
  {
    id: '12',
    title: 'ChatGPT',
    description:
      'ChatGPT is OpenAI\'s advanced conversational AI assistant powered by GPT-4, capable of understanding and generating human-like text. DQ uses ChatGPT to enhance productivity across content creation, research, coding assistance, data analysis, and problem-solving, empowering teams to work smarter and faster.',
    category: 'AI Tools',
    serviceType: 'Requisition',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    toolCategory: 'llm',
    accessType: 'request_access',
    pricing: 'paid',
    provider: {
      name: 'Digital Innovation',
      logoUrl: '/DWS-Logo.png',
      description:
        'Digital Innovation team provides access to cutting-edge AI tools including ChatGPT for enhanced productivity and intelligent automation.',
    },
    duration: '1-2 business days',
    price: 'Licensed',
    details: [
      'Request access to ChatGPT Enterprise',
      'Advanced conversational AI powered by GPT-4',
      'Content generation and creative writing assistance',
      'Code generation, debugging, and technical support',
      'Data analysis and document summarization',
      'Multi-language support and translation',
      'Image understanding and visual analysis',
      'Includes onboarding and best practices guide',
    ],
    tags: ['Digital Innovation', 'Online', 'AI Tools'],
    featuredImageUrl: '/images/services/chat-gpt.jpg',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
    homepageUrl: 'https://chat.openai.com',
  },
  {
    id: '20',
    title: 'Mokkup.ai',
    description:
      'Mokkup.ai is an AI-powered mockup generator that creates professional product visualizations in seconds. DQ uses Mokkup.ai to streamline our design workflow, enabling designers and marketers to quickly produce stunning mockups for presentations, marketing campaigns, and product showcases without manual editing.',
    category: 'AI Tools',
    serviceType: 'Requisition',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    toolCategory: 'content_generators',
    accessType: 'request_access',
    pricing: 'paid',
    provider: {
      name: 'Digital Innovation',
      logoUrl: '/DWS-Logo.png',
      description:
        'Digital Innovation team provides access to cutting-edge AI-powered design and mockup tools for enhanced creative productivity.',
    },
    duration: '1-2 business days',
    price: 'Licensed',
    details: [
      'Request access to Mokkup.ai platform',
      'AI-powered mockup generation in seconds',
      'Smart background removal and image enhancement',
      'Thousands of device and product templates',
      'Batch processing for multiple images',
      'High-resolution export up to 4K quality',
      'Mobile and desktop applications',
      'Includes onboarding and design guidelines',
    ],
    tags: ['Digital Innovation', 'Online', 'AI Tools'],
    featuredImageUrl: '/images/services/mokkup.png',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
    homepageUrl: 'https://mokkup.ai',
  },
  {
    id: '21',
    title: 'Voiceflow',
    description:
      'Voiceflow is a leading platform for building AI-powered conversational agents with visual workflows. DQ uses Voiceflow to automate customer support and scale interactions through intelligent voice and chat agents, reducing response times while maintaining high-quality, human-like customer experiences across multiple channels.',
    category: 'AI Tools',
    serviceType: 'Requisition',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    toolCategory: 'content_generators',
    accessType: 'request_access',
    pricing: 'paid',
    provider: {
      name: 'Digital Innovation',
      logoUrl: '/DWS-Logo.png',
      description:
        'Digital Innovation team provides access to advanced conversational AI platforms for building intelligent customer service agents and automating interactions.',
    },
    duration: '1-2 business days',
    price: 'Licensed',
    details: [
      'Request access to Voiceflow Enterprise platform',
      'Build voice AI agents for human-like phone interactions',
      'Design chat agents with deep customization capabilities',
      'Visual conversation flow designer for rapid development',
      'Deploy across phone, web, mobile, and messaging channels',
      'Integrate with Salesforce, Zendesk, Shopify, and more',
      'SOC-2 and GDPR compliant security features',
      'Includes team collaboration and analytics tools',
    ],
    tags: ['Digital Innovation', 'Online', 'AI Tools'],
    featuredImageUrl: '/images/services/voice-flow.jpg',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
    homepageUrl: 'https://www.voiceflow.com',
  },
  {
    id: '13',
    title: 'Leave Application',
    description:
      'Submit leave requests using the DQ Approvals app for annual leave (30 days), sick leave (5 days), emergency leave, maternity leave (45 days), or compassionate leave (3-5 days). All associates must obtain line manager approval and follow standardized procedures. Leaves exceeding one day require handover catalog submission with sign-off.',
    category: 'Employee Services',
    serviceType: 'Requisition',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    services: ['Human Resources'],
    documentType: ['Policies', 'Forms'],
    provider: {
      name: 'HR',
      logoUrl: '/leave.jpg',
      description:
        'DQ Human Resources manages leave policies and ensures fair, consistent application of leave rules across all departments and business units.',
    },
    duration: 'Varies by leave type',
    price: 'Free',
    details: [
      'Apply via Approvals app after capturing line manager approval',
      '30 calendar days annual leave (no carryover, post-probation)',
      '5 annual sick leave days with medical certificate for multiple days',
      '45 days maternity leave available before/after childbirth',
      '3-5 days compassionate leave for family illness or loss',
      'Complete handover catalog for leaves exceeding one day',
    ],
    tags: ['HR', 'Online', 'Business'],
    featuredImageUrl: '/images/services/leave.jpg',
    requestUrl: 'https://teams.microsoft.com/l/app/7c316234-ded0-4f95-8a83-8453d0876592?source=app-bar-share-entrypoint',
  },
  {
    id: '14',
    title: 'Shifts Allocation',
    description:
      'View and manage your work shifts using the DQ Shifts app. Confirm assigned shifts by Friday each week, request shift changes through your line manager, and clock in/out on time. All shifts are published by Wednesday. Supports morning, evening, split shifts, and remote work schedules with 100% compliance requirements.',
    category: 'Employee Services',
    serviceType: 'Query',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    services: ['Human Resources', 'Administration'],
    documentType: ['Policies', 'Guidelines'],
    provider: {
      name: 'Admin',
      logoUrl: '/DWS-Logo.png',
      description:
        'DQ Admin manages shift allocations, processes shift changes, and tracks attendance to ensure operational efficiency and fair distribution of work schedules.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'Confirm assigned shifts immediately upon publication (by Friday)',
      'Request shift changes via line manager with valid reasons',
      'Clock in and out at designated times for each shift',
      'Shifts published every Wednesday for the following week',
      'Support for morning, evening, split shifts, and remote shifts',
      '100% compliance required for shift confirmation and attendance',
    ],
    tags: ['Admin', 'Online', 'Business'],
    featuredImageUrl: '/images/services/shifts-allocation.jpg',
    requestUrl: 'https://teams.microsoft.com/l/app/42f6c1da-a241-483a-a3cc-4f5be9185951?source=app-bar-share-entrypoint',
  },
  {
    id: '15',
    title: 'Reimbursements',
    description:
      'Request reimbursement for economy class return flight tickets to your home country. Submit requests at least one month before travel with three quotes from reputable platforms. Reimbursement is based on average ticket cost. Admin reviews eligibility, Ops Lead approves bookings, and Finance processes payments. Book flights at least two weeks before travel.',
    category: 'Employee Services',
    serviceType: 'Requisition',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    services: ['Finance', 'Human Resources', 'Administration'],
    documentType: ['Policies', 'Forms', 'Guidelines'],
    provider: {
      name: 'Finance',
      logoUrl: '/DWS-Logo.png',
      description:
        'DQ Finance processes flight ticket reimbursements for eligible permanently employed associates, ensuring transparency, fairness, and compliance with budget guidelines.',
    },
    duration: '2-4 weeks',
    price: 'Based on average ticket cost',
    details: [
      'Economy class return tickets from Dubai to home country',
      'Submit request at least one month before travel with three quotes',
      'Book flights at least two weeks before travel date',
      'Reimbursement based on average of three quotes from reputable platforms',
      'Associate pays difference if ticket exceeds average cost',
      'Applies to permanently employed associates who meet eligibility criteria',
    ],
    tags: ['Finance', 'Online', 'Business'],
    featuredImageUrl: '/images/services/ticket-reimbursement.jpg',
    requestUrl: 'https://teams.microsoft.com/l/app/7c316234-ded0-4f95-8a83-8453d0876592?source=app-bar-share-entrypoint',
  },
  {
    id: '16',
    title: 'Staff Requisition',
    description:
      'DigitalQatalyst (DQ) is strengthening its Centre of Excellence (CoE) to embed consistent quality, performance, and agility across the organization. As DQ grows, the CoE ensures unified standards, reduces inefficiencies, and reinforces strong governance through the QPMS framework. To support this mandate, the CoE requires analysts with strong analytical and operational skills who can work cross-functionally, provide clear insights, and translate performance frameworks into measurable impact.',
    category: 'Employee Services',
    serviceType: 'Requisition',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    services: ['Human Resources'],
    documentType: ['Forms', 'Policies'],
    provider: {
      name: 'HR',
      logoUrl: '/DWS-Logo.png',
      description:
        'DQ Human Resources manages staff requisition processes to ensure staffing needs align with organizational priorities, budget availability, and operational requirements.',
    },
    duration: '2-4 weeks',
    price: 'Free',
    details: [
      'Submit demand card with role purpose, responsibilities, and competencies',
      'Line manager validates business need and budget availability',
      'HR reviews and validates compliance with staffing policies',
      'Supports permanent, contract, and temporary staffing needs',
      'Full visibility and traceability throughout recruitment process',
      'Incomplete submissions may be returned for clarification',
    ],
    tags: ['HR', 'Online', 'Business'],
    featuredImageUrl: '/images/services/staff-requisition.jpg',
    requestUrl: 'https://teams.microsoft.com/l/app/7c316234-ded0-4f95-8a83-8453d0876592?source=app-bar-share-entrypoint',
  },
  {
    id: '17',
    title: 'Supabase Full-Stack Development Prompt',
    description:
      'Comprehensive development guidelines for building modern full-stack applications with TypeScript, React, Next.js, Expo, Supabase, and related technologies. Includes best practices for code structure, state management, testing, and deployment in monorepo setups.',
    category: 'Prompt Library',
    serviceType: 'Self-Service',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    promptType: 'dev_prompts',
    technologies: ['TypeScript', 'React', 'Next.js', 'Expo', 'Supabase', 'Zustand', 'TanStack Query', 'Stripe'],
    provider: {
      name: 'Digital Innovation',
      logoUrl: '/DWS-Logo.png',
      description:
        'Digital Innovation team curates and maintains a library of AI prompts and development guidelines to accelerate project delivery and ensure consistent code quality.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'Complete TypeScript and React development guidelines',
      'Supabase integration best practices',
      'State management with Zustand and TanStack Query',
      'Cross-platform development with Expo and React Native',
      'Stripe payment and subscription model implementation',
      'Monorepo management with Turbo',
      'Testing, performance optimization, and error handling patterns',
    ],
    tags: ['Prompt Library', 'Development', 'Full-Stack', 'TypeScript', 'Supabase'],
    featuredImageUrl: '/images/services/react-supabase.jpg',
    sourceUrl: 'https://cursor.directory/rules/supabase',
  },
  {
    id: '18',
    title: 'Next.js 14 + Supabase Full-Stack Prompt',
    description: 'Expert guidelines for building modern full-stack applications with Next.js 14, Supabase, and TypeScript. Focus on React Server Components, SSR features, clean code architecture, and production-ready best practices.',
    category: 'Prompt Library',
    serviceType: 'Self-Service',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    promptType: 'dev_prompts',
    technologies: ['Next.js 14', 'Supabase', 'TypeScript', 'TailwindCSS', 'React Server Components'],
    provider: {
      name: 'Digital Innovation',
      logoUrl: '/DWS-Logo.png',
      description: 'Digital Innovation team curates and maintains a library of AI prompts and development guidelines to accelerate project delivery and ensure consistent code quality.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'Next.js 14 with App Router best practices',
      'Supabase integration and authentication patterns',
      'React Server Components and SSR optimization',
      'TypeScript with strict typing and interfaces',
      'TailwindCSS styling conventions',
      'Error handling and loading states',
      'Production-ready code standards',
    ],
    tags: ['Prompt Library', 'Next.js', 'Supabase', 'TypeScript', 'Full-Stack'],
    featuredImageUrl: '/images/services/nextjs.jpg',
    sourceUrl: 'https://cursor.directory/monorepo-tamagui',
  },
  {
    id: '19',
    title: 'SvelteKit + Supabase Full-Stack Prompt',
    description: 'Expert guidelines for building modern full-stack applications with SvelteKit, Supabase, Tailwind, and TypeScript. Focuses on SvelteKit SSR features, clean code architecture, and production-ready best practices with minimal client-side components.',
    category: 'Prompt Library',
    serviceType: 'Self-Service',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    promptType: 'dev_prompts',
    technologies: ['SvelteKit', 'Supabase', 'TypeScript', 'Tailwind', 'Svelte'],
    provider: {
      name: 'Digital Innovation',
      logoUrl: '/DWS-Logo.png',
      description: 'Digital Innovation team curates and maintains a library of AI prompts and development guidelines to accelerate project delivery and ensure consistent code quality.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'SvelteKit SSR and server-side rendering best practices',
      'Supabase integration and authentication patterns',
      'Svelte stores for global state management',
      'TypeScript with enhanced type safety',
      'Tailwind CSS styling conventions',
      'Error handling and loading states',
      'Kebab-case component naming conventions',
    ],
    tags: ['Prompt Library', 'SvelteKit', 'Supabase', 'TypeScript', 'Full-Stack'],
    featuredImageUrl: '/images/services/supabase.png',
    sourceUrl: 'https://cursor.directory/rules/sveltekit',
  },
  {
    id: '22',
    title: 'AI QA Engineer & Journey Reviewer Prompt',
    description:
      'A specialized prompt for an AI QA engineer that reads real implementation, derives behaviors from code, and generates focused test plans across functional, journey, rendering, and error-handling dimensions.',
    category: 'Prompt Library',
    serviceType: 'Self-Service',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    promptType: 'qa_prompts',
    technologies: ['React', 'TypeScript', 'TailwindCSS', 'Vite'],
    provider: {
      name: 'Digital Innovation',
      logoUrl: '/DWS-Logo.png',
      description:
        'Digital Innovation team curates and maintains a library of AI prompts and development guidelines to accelerate project delivery and ensure consistent code quality.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'Analyze production code to infer actual implemented behavior',
      'Generate structured feature inventories from real routes, components, and APIs',
      'Create functional, journey, rendering, and error-handling test cases',
      'Focus on observable behavior instead of assumptions or undocumented intent',
      'Produce QA deliverables suitable for manual or automated execution',
    ],
    tags: ['Prompt Library', 'QA', 'Testing', 'Journeys'],
    featuredImageUrl: '/images/services/ai.jpg',
    sourceUrl: null,
  },
  {
    id: 'dw-001',
    title: 'Portfolio Analysis',
    description: 'Service strategists use ChatGPT/Copilot to analyze service performance data and generate insights.',
    category: 'Digital Worker',
    serviceType: 'Query',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    serviceDomains: ['backoffice_operations'],
    aiMaturityLevel: 'level_1',
    provider: {
      name: 'Digital Worker',
      logoUrl: '/DWS-Logo.png',
      description: 'Digital Worker services provide AI-powered automation and intelligent assistance across the enterprise.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'Strategists copy/paste service data into AI for analysis',
      'AI identifies patterns and generates summary insights',
      'Recommendations reviewed and validated by humans',
      'No direct integration with service data sources',
    ],
    tags: ['Digital Worker', 'AI Maturity Level 1', 'Backoffice Operations'],
    featuredImageUrl: '/images/services/portfolio-analysis.jpg',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
  },
  {
    id: 'dw-002',
    title: 'Portfolio Intelligence',
    description: 'AI embedded in portfolio management platform continuously analyzes service performance.',
    category: 'Digital Worker',
    serviceType: 'Query',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    serviceDomains: ['backoffice_operations'],
    aiMaturityLevel: 'level_2',
    provider: {
      name: 'Digital Worker',
      logoUrl: '/DWS-Logo.png',
      description: 'Digital Worker services provide AI-powered automation and intelligent assistance across the enterprise.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'AI integrated directly into service portfolio management tool',
      'Continuous monitoring of service metrics',
      'Automated anomaly detection',
      'Proactive recommendations surfaced in dashboard',
    ],
    tags: ['Digital Worker', 'AI Maturity Level 2', 'Backoffice Operations'],
    featuredImageUrl: '/images/services/portfolio-intelligence.jpg',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
  },
  {
    id: 'dw-003',
    title: 'Portfolio Optimization',
    description: 'Unified AI platform orchestrates end-to-end service portfolio strategy integrating enterprise data.',
    category: 'Digital Worker',
    serviceType: 'Query',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    serviceDomains: ['backoffice_operations'],
    aiMaturityLevel: 'level_3',
    provider: {
      name: 'Digital Worker',
      logoUrl: '/DWS-Logo.png',
      description: 'Digital Worker services provide AI-powered automation and intelligent assistance across the enterprise.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'AI accesses unified enterprise knowledge graph',
      'Continuously evaluates entire service portfolio holistically',
      'Simulates portfolio scenarios against strategic objectives',
      'Agentic AI can request additional data',
    ],
    tags: ['Digital Worker', 'AI Maturity Level 3', 'Backoffice Operations'],
    featuredImageUrl: '/images/services/portfolio-optimization.jpg',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
  },
  {
    id: 'dw-004',
    title: 'Strategy Advisor',
    description: 'AI operates as a strategic partner, engaging in strategic dialogue and challenging assumptions.',
    category: 'Digital Worker',
    serviceType: 'Query',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    serviceDomains: ['backoffice_operations'],
    aiMaturityLevel: 'level_4',
    provider: {
      name: 'Digital Worker',
      logoUrl: '/DWS-Logo.png',
      description: 'Digital Worker services provide AI-powered automation and intelligent assistance across the enterprise.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'AI participates in strategy sessions as "virtual board member"',
      'Challenges strategic assumptions with data',
      'Proposes alternative strategic scenarios',
      'Makes autonomous investment decisions up to $500K',
    ],
    tags: ['Digital Worker', 'AI Maturity Level 4', 'Backoffice Operations'],
    featuredImageUrl: '/images/services/strategy-advisor.jpg',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
  },
  {
    id: 'dw-005',
    title: 'Autonomous Strategy',
    description: 'AI autonomously discovers, designs, tests, and launches new services with minimal human intervention.',
    category: 'Digital Worker',
    serviceType: 'Query',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    serviceDomains: ['backoffice_operations'],
    aiMaturityLevel: 'level_5',
    provider: {
      name: 'Digital Worker',
      logoUrl: '/DWS-Logo.png',
      description: 'Digital Worker services provide AI-powered automation and intelligent assistance across the enterprise.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'AI continuously scans for unmet customer needs',
      'Designs new service concepts autonomously',
      'Tests services in digital twin environment',
      'Executes pilot programs and scales successes',
    ],
    tags: ['Digital Worker', 'AI Maturity Level 5', 'Backoffice Operations'],
    featuredImageUrl: '/images/services/autonomous-strategy.jpg',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
  },
  {
    id: 'dw-006',
    title: 'Requirements Elicitation',
    description: 'Requirements analysts use AI to prepare questions, analyze inputs, and draft documentation.',
    category: 'Digital Worker',
    serviceType: 'Query',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    serviceDomains: ['backoffice_operations'],
    aiMaturityLevel: 'level_1',
    provider: {
      name: 'Digital Worker',
      logoUrl: '/DWS-Logo.png',
      description: 'Digital Worker services provide AI-powered automation and intelligent assistance across the enterprise.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'AI helps generate interview questions',
      'Analysts paste meeting transcripts for summarization',
      'AI suggests requirements based on input',
      'AI drafts standard requirement documents',
    ],
    tags: ['Digital Worker', 'AI Maturity Level 1', 'Backoffice Operations'],
    featuredImageUrl: '/images/services/requirements-elicitation.jpg',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
  },
  {
    id: 'dw-007',
    title: 'Design Automation',
    description: 'Platform with integrated AI generates service designs, applies standards, and validates quality.',
    category: 'Digital Worker',
    serviceType: 'Query',
    deliveryMode: 'Online',
    businessStage: 'All Stages',
    serviceDomains: ['backoffice_operations'],
    aiMaturityLevel: 'level_2',
    provider: {
      name: 'Digital Worker',
      logoUrl: '/DWS-Logo.png',
      description: 'Digital Worker services provide AI-powered automation and intelligent assistance across the enterprise.',
    },
    duration: 'Immediate',
    price: 'Free',
    details: [
      'AI generates complete service designs from requirements',
      'Automatically applies enterprise architecture patterns',
      'Validates against security and compliance policies',
      'Identifies reusable components',
    ],
    tags: ['Digital Worker', 'AI Maturity Level 2', 'Backoffice Operations'],
    featuredImageUrl: '/images/services/design-automation.jpg',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
  },
  {
    id: 'ghc-tmaas',
    title: 'GHC Transformation Management',
    description: 'Comprehensive transformation management service that provides expertise and tools to design and deploy a formidable Digital Business Platform (DBP) effectively, making the journey clear and streamlined for organizations evolving into Digital Cognitive Organizations.',
    category: 'Business',
    serviceType: 'Consulting',
    deliveryMode: 'Hybrid',
    businessStage: 'All Stages',
    userCategory: ['Employee', 'Manager', 'Leadership'],
    technicalCategory: ['Strategy', 'Transformation', 'Digital Platform'],
    deviceOwnership: ['Company Device'],
    provider: {
      name: 'GHC Transformation Team',
      logoUrl: '/DWS-Logo.png',
      description: 'Golden Honeycomb Transformation team provides expert guidance and tools for digital transformation and DBP implementation.',
    },
    duration: '3-12 months',
    price: 'Custom Quote',
    details: [
      'Design and deploy Digital Business Platform (DBP)',
      'Expert guidance on transformation journey',
      'Integrated suite of advanced technologies implementation',
      'Industry pinnacle positioning strategies',
      'Clear and streamlined transformation roadmap',
      'Comprehensive change management support',
      'Technology stack optimization and integration',
      'Organizational capability development'
    ],
    tags: ['GHC', 'Transformation', 'Digital Platform', 'Consulting', 'Hybrid'],
    featuredImageUrl: '/images/guidelines-content.PNG',
    requestUrl: 'https://forms.office.com/pages/responsepage.aspx?id=Db2eGYYpPU-GWUOIxbKnJCT2lmSqJbRJkPMD7v6Rk31UNjlVQjlRSjFBUk5MSTNGUDJNTjk0S1NMVi4u&route=shorturl',
  },
]
