/**
 * Script to generate SQL seed files from TypeScript data files
 * Run with: node scripts/generate-seeds.js
 * 
 * This script extracts data from TypeScript files and generates SQL INSERT statements
 */

const fs = require('fs');
const path = require('path');

// Helper function to escape SQL strings
function escapeSQL(str) {
  if (!str) return 'NULL';
  return `'${str.replace(/'/g, "''").replace(/\n/g, '\\n').replace(/\r/g, '\\r')}'`;
}

// Helper function to convert array to PostgreSQL array syntax
function arrayToSQL(arr) {
  if (!arr || arr.length === 0) return "'{}'";
  return `ARRAY[${arr.map(item => escapeSQL(item)).join(', ')}]`;
}

// Helper function to generate news seed SQL
function generateNewsSeed() {
  const newsFilePath = path.join(__dirname, '../src/data/media/news.ts');
  const newsContent = fs.readFileSync(newsFilePath, 'utf8');
  
  // Extract NEWS array using regex
  const newsMatch = newsContent.match(/export const NEWS: NewsItem\[\] = \[([\s\S]*?)\];/);
  if (!newsMatch) {
    console.error('Could not find NEWS array in news.ts');
    return;
  }
  
  // Parse the array content (simplified - this is a basic parser)
  // In production, you might want to use a proper TypeScript parser
  console.log('Found NEWS array, extracting items...');
  console.log('NOTE: Manual extraction may be needed for complex content');
  
  // Output instructions
  const output = `-- This file was generated by scripts/generate-seeds.js
-- Manual editing may be required for complex content strings

-- To complete this file:
-- 1. Copy all items from src/data/media/news.ts NEWS array
-- 2. Convert each item to SQL INSERT format
-- 3. Use escapeSQL() helper to escape strings
-- 4. Use arrayToSQL() helper for arrays
`;
  
  fs.writeFileSync(
    path.join(__dirname, '../supabase/seed-news-generated.sql'),
    output
  );
  
  console.log('Generated seed-news-generated.sql (template)');
  console.log('Note: Full automation requires TypeScript parser. Manual completion recommended.');
}

// Main execution
if (require.main === module) {
  console.log('Generating seed files...');
  generateNewsSeed();
  console.log('Done!');
}

module.exports = { escapeSQL, arrayToSQL };

